var masterGoalList = 
[{"name": "7 keyblades"},
{"name": "7 unique staffs"},
{"name": "7 unique shields"},
{"name": "7 unique armors"},
{"name": "7 unique accessories"},
{"name": "10000 Munny"},
{"name": "Have 20 AP Boosts in your inventory"},
{"name": "Have 30 Potions in your inventory"},
{"name": "Have 1 of every magic element"},
{"name": "Use a tent"},
{"name": "Use one of any mega item"},
{"name": "Report 1, 2, or 3"},
{"name": "Report 4, 5, or 6"},
{"name": "Report 10, 11, 12, or 13"},
{"name": "Activate Anti-Form 13 times"},
{"name": "Use an auto form"},
{"name": "Use every limit in Limit Form once"},
{"name": "Valor Level 2"},
{"name": "Valor Level 3"},
{"name": "Valor Level 4"},
{"name": "Valor Level 5"},
{"name": "Valor Level 6"},
{"name": "Valor Level 7"},
{"name": "Wisdom Level 2"},
{"name": "Wisdom Level 3"},
{"name": "Wisdom Level 4"},
{"name": "Wisdom Level 5"},
{"name": "Wisdom Level 6"},
{"name": "Wisdom Level 7"},
{"name": "Limit Level 2"},
{"name": "Limit Level 3"},
{"name": "Limit Level 4"},
{"name": "Limit Level 5"},
{"name": "Limit Level 6"},
{"name": "Limit Level 7"},
{"name": "Master Level 2"},
{"name": "Master Level 3"},
{"name": "Master Level 4"},
{"name": "Master Level 5"},
{"name": "Master Level 6"},
{"name": "Master Level 7"},
{"name": "Final Level 2"},
{"name": "Final Level 3"},
{"name": "Final Level 4"},
{"name": "Final Level 5"},
{"name": "Final Level 6"},
{"name": "Final Level 7"},
{"name": "Level 20"},
{"name": "Level 25"},
{"name": "Level 30"},
{"name": "Level 35"},
{"name": "Level 40"},
{"name": "Level 45"},
{"name": "Level 50"},
{"name": "Summon Level 3"},
{"name": "Summon Level 4"},
{"name": "Summon Level 5"},
{"name": "Synth 3 Items"},
{"name": "Reach Moogle Level 2"},
{"name": "Collect all chests in Twilight Town"},
{"name": "Collect all chests in Hollow Bastion"},
{"name": "Collect all chests in Beast's Castle"},
{"name": "Collect all chests in Olympus Coliseum"},
{"name": "Collect all chests in Agrabah"},
{"name": "Collect all chests in Land of Dragons"},
{"name": "Collect all chests in 100 Acre Wood"},
{"name": "Collect all chests in Pride Lands"},
{"name": "Collect all chests in Disney Castle"},
{"name": "Collect all chests in Timeless River"},
{"name": "Collect all chests in Halloween Town"},
{"name": "Collect all chests in Port Royal"},
{"name": "Collect all chests in Space Paranoids"},
{"name": "Mail Delivery job"},
{"name": "Poster Duty job"},
{"name": "Cargo Climb job"},
{"name": "Grandstander job"},
{"name": "Bumble Buster job"},
{"name": "Junk Sweep job"},
{"name": "Use capsule prize on a Bulky Vendor"},
{"name": "Atlantica tutorial"},
{"name": "Buy something from Elmina (TT Moogle)"},
{"name": "Buy something from Mog (HB Moogle)"},
{"name": "Buy something form Kupo (LOD Moogle)"},
{"name": "Buy something form Monty (BC Moogle)"},
{"name": "Buy something from Mosh (OC Moogle)"},
{"name": "Buy something from Mogjiro (DC Moogle)"},
{"name": "Buy something from Mogtaro (TR Moogle)"},
{"name": "Buy something from Morlock (PR Moogle)"},
{"name": "Buy something from Gumo (HT Moogle)"},
{"name": "Buy something from Mojito (AG Moogle)"},
{"name": "Buy something from Kumop (PL Moogle)"},
{"name": "Buy something from Artemicion (SP Moogle)"},
{"name": "Buy something from Stiltzkin (TWTNW Moogle)"},
{"name": "Use 7 different limits"},
{"name": "Use Beast's limit"},
{"name": "Use Mulan's limit"},
{"name": "Use Auron's limit"},
{"name": "Use Jack Sparrow's limit"},
{"name": "Use Aladdin's limit"},
{"name": "Use Jack Skellington's limit"},
{"name": "Use Simba's limit"},
{"name": "Use Tron's limit"},
{"name": "Use a summon limit"},
{"name": "Obtain a Struggle weapon"},
{"name": "Defeat Twilight Thorn"},
{"name": "Defeat Seifer in the back alley as Roxas"},
{"name": "Win the Struggle against Hayner"},
{"name": "Win the Struggle against Vivi"},
{"name": "Defeat Axel 1 as Roxas"},
{"name": "Win the Struggle against Setzer"},
{"name": "Go to Sunset Hill as Roxas"},
{"name": "Enter Namine's Room as Roxas"},
{"name": "Defeat Axel 2 as Roxas"},
{"name": "Destroy all tents in Shang's Camp"},
{"name": "Complete all of Shang's missions"},
{"name": "Complete the mountain climb in Land of Dragons"},
{"name": "Beat cave fight in LOD1"},
{"name": "Beat summit fight in LOD1"},
{"name": "Defeat Shan Yu"},
{"name": "Defeat Riku in LOD"},
{"name": "Go to Throne Room in LOD"},
{"name": "Defeat Storm Rider"},
{"name": "Beat Hades Escape"},
{"name": "Defeat Cerberus"},
{"name": "Complete Phil's urn training"},
{"name": "Beat Demyx in OC1"},
{"name": "Beat Pete in OC1"},
{"name": "Defeat Hydra"},
{"name": "Beat Hades Cup in OC2"},
{"name": "Auron's Statue check in OC2"},
{"name": "Defeat Hades"},
{"name": "Destroy the armor statues in the West Hall of Beast's Castle"},
{"name": "Defeat Thresholder"},
{"name": "Complete Cogsworth minigame"},
{"name": "Examine Beast's rose"},
{"name": "Defeat Dark Thorn"},
{"name": "Rumbling Rose check in BC2"},
{"name": "Defeat Xaldin in Beast's Castle"},
{"name": "Minnie Escort"},
{"name": "Defeat Old Pete"},
{"name": "Beat construction window in TR"},
{"name": "Beat Lilliput window in TR"},
{"name": "Beat fire window in TR"},
{"name": "Go to Mickey's house in TR"},
{"name": "Complete all windows in TR"},
{"name": "Defeat Boat Pete"},
{"name": "Defeat Future Pete"},
{"name": "Beat 1min timed fight in PR1"},
{"name": "Beat an ambush on the boat in Port Royal"},
{"name": "Complete boat fight in PR1"},
{"name": "Beat barrels section in PR1"},
{"name": "Defeat Barbossa"},
{"name": "Defeat Grim Reaper 1"},
{"name": "Collect all medallions from the gamblers in PR2"},
{"name": "Defeat Grim Reaper 2"},
{"name": "Destroy a stall for a puzzle piece in Agrabah"},
{"name": "Jump on top of the Tiger Head in Agrabah"},
{"name": "Enter the Cave of Wonders"},
{"name": "Beat falling segment in AG1"},
{"name": "Open both treasures in the Treasure Room in Agrabah"},
{"name": "Defeat Twin Lords"},
{"name": "Ride on the Carpet in Agrabah"},
{"name": "Grab all 3 puzzle pieces in the Sandswept Ruins"},
{"name": "Open both treasures in the ruined chamber in Agrabah"},
{"name": "Defeat Genie Jafar"},
{"name": "Spin the carousel in Xmas Town"},
{"name": "Defeat Prison Keeper"},
{"name": "Defeat Oogie Boogie"},
{"name": "Beat Lock, Shock, and Barrel in the present factory"},
{"name": "Beat the Present minigame in Xmas Town"},
{"name": "Defeat the Experiment"},
{"name": "Talk to Rafiki"},
{"name": "Beat the Hyenas in PL1"},
{"name": "Defeat Scar"},
{"name": "Beat the Hyenas in PL2"},
{"name": "Defeat Groundshaker"},
{"name": "Beat the cube minigame in SP1"},
{"name": "Complete Light Cycle minigame"},
{"name": "Complete screens in SP1"},
{"name": "Defeat Hostile Program"},
{"name": "Beat light cycle fight in SP2"},
{"name": "Beat 2nd forced fight (w/ Devastators) in SP2"},
{"name": "Defeat Solar Sailer Heartless"},
{"name": "Defeat Sark"},
{"name": "Defeat MCP"},
{"name": "Talk to Scrooge"},
{"name": "Buy something from Huey Duck"},
{"name": "Buy something from Dewey Duck"},
{"name": "Buy something from Louie Duck"},
{"name": "Beat Bailey fight in HB"},
{"name": "Reach Ansem's study in Hollow Bastion"},
{"name": "Open Tifa's chest in Hollow Bastion"},
{"name": "Defeat Demyx in HB"},
{"name": "Fight with Yuffie in HB and win"},
{"name": "Fight with Tifa in HB and win"},
{"name": "Fight with Cloud in HB and win"},
{"name": "Beat 1k"},
{"name": "Open the Gull Wing chest in HB"},
{"name": "Enter Yen Sid's Tower"},
{"name": "Speak to the fairies at Yen Sid's Tower"},
{"name": "Beat sandlot fight in TT2"},
{"name": "Beat mansion fight in TT3"},
{"name": "Grab the puzzle piece in the pod room in TT"},
{"name": "Beat the Betwixt and Between fight"},
{"name": "Defeat Hayner as Sora"},
{"name": "Jump on top of a tram in Twilight Town"},
{"name": "Grab both puzzle pieces on Sunset Hill"},
{"name": "Examine the truck in TWTNW"},
{"name": "Proof of Existence"},
{"name": "Defeat Roxas in TWTNW"},
{"name": "Defeat Xigbar in TWTNW"},
{"name": "Defeat Luxord in TWTNW"},
{"name": "Defeat Saix in TWTNW"},
{"name": "Defeat Xemnas in TWTNW"},
{"name": "Save Piglet"},
{"name": "Reach the bottom of Honey Pot Hill"},
{"name": "Beat Balloon Bounce with Tigger and Roo"},
{"name": "Find Pooh in the Spooky Cave"},
{"name": "Yeet the Bear"},
{"name": "Examine Rabbit's clothesline"},
{"name": "Take Roxas's keyblades"},
{"name": "Play a game with Luxord"},
{"name": "Witness Saix enter his berserk state"},
{"name": "Examine one of Namine's drawings"},
{"name": "Touch the beam in Twilight Town"},
{"name": "Turn one portal pink"},
{"name": "Obtain Beast as a party member"},
{"name": "Obtain Jack Skellington as a party member"},
{"name": "Obtain Simba as a party member"},
{"name": "Obtain Jack Sparrow as a party member"},
{"name": "Obtain Riku as a party member"},
{"name": "Obtain Aladdin as a party member"},
{"name": "Obtain Auron as a party member"},
{"name": "Obtain Mulan as a party member"},
{"name": "Collect 10 puzzle pieces"},
{"name": "Collect 20 puzzle pieces"},
{"name": "Collect 30 puzzle pieces"},
{"name": "Collect 40 puzzle pieces"},
{"name": "Collect 50 puzzle pieces"},
{"name": "Complete 1 Puzzle"},
{"name": "Complete 2 Puzzles"},
{"name": "Complete Awakening Puzzle"},
{"name": "Complete Heart Puzzle"},
{"name": "Complete Duality Puzzle"},
{"name": "Complete Frontier Puzzle"},
{"name": "Complete Daylight Puzzle"},
{"name": "Complete Sunset Puzzle"},
{"name": "Collect 2 Puzzle Pieces in Triton's Throne"},
{"name": "Finny Fun"},
{"name": "Part of Your World"},
{"name": "Under the Sea"},
{"name": "Ursula's Revenge"},
{"name": "A New Day is Dawning"},
{"name": "Shroom 1 (TWTNW)"},
{"name": "Shroom 2 (Halloween Town)"},
{"name": "Shroom 3 (Beast's Castle)"},
{"name": "Shroom 4 (Land of Dragons)"},
{"name": "Shroom 5 (Agrabah)"},
{"name": "Shroom 6 (Olympus Coliseum)"},
{"name": "Shroom 7 (Twilight Town Tunnelway)"},
{"name": "Shroom 8 (Yen Sid's Tower)"},
{"name": "Shroom 9 (Hollow Bastion)"},
{"name": "Shroom 10 (Port Royal)"},
{"name": "Shroom 11 (Timeless River)"},
{"name": "Shroom 12 (Twilight Town Mansion)"},
{"name": "Shroom 13 (Proof of Peace Check)"},
{"name": "Beat Pain and Panic Cup"},
{"name": "Beat Cerberus Cup"},
{"name": "Beat Titan Cup"},
{"name": "Beat Goddess of Fate Cup"},
{"name": "Beat the 1st CoR fight"},
{"name": "Turn the valves in CoR"},
{"name": "Beat the 2nd CoR fight"},
{"name": "Get to the Engine Chamber in CoR"},
{"name": "Open the last chest in CoR"},
{"name": "Beat Transport to Remembrance"},
{"name": "Defeat AS Zexion"},
{"name": "Defeat AS Larxene"},
{"name": "Defeat AS Vexen"},
{"name": "Defeat AS Lexaeus"},
{"name": "Defeat AS Marluxia"},
{"name": "Defeat Data Roxas"},
{"name": "Defeat Data Demyx"},
{"name": "Defeat Data Zexion"},
{"name": "Defeat Data Xigbar"},
{"name": "Defeat Data Saix"},
{"name": "Defeat Data Vexen"},
{"name": "Defeat Data Larxene"},
{"name": "Defeat Data Axel"},
{"name": "Defeat Data Xaldin"},
{"name": "Defeat Data Lexaeus"},
{"name": "Defeat Data Marluxia"},
{"name": "Defeat Data Luxord"},
{"name": "Defeat Data Xemnas"},
{"name": "Defeat Sephiroth"},
{"name": "Defeat Terra"},
{"name": "Score 500 on SB Street Rave (Twilight Town)"},
{"name": "Score 100 on SB Freestyle (Hollow Bastion)"},
{"name": "Finish in 60s on SB Time Attack (Port Royal)"},
{"name": "Get 10 Crystals in 60s on SB Sand Slider (Agrabah)"},
{"name": "Score 500 on SB Workshop Rave (Halloween Town)"},
{"name": "Clash with Xemnas"},
{"name": "Enter the Laser Dome"},
{"name": "Use all of Genie's Limits"},
{"name": "Dual Wield Oathkeeper and Oblivion"},
{"name": "Obtain a -ga spell"},
{"name": "Bronze Crown"},
{"name": "Silver Crown"},
{"name": "Gold Crown"},
{"name": "Defeat Final Xemnas"},
{"name": "Obtain 3 Recipes"},
{"name": "Synth 1 Recipe Item"},
{"name": "Fire"},
{"name": "Blizzard"},
{"name": "Thunder"},
{"name": "Cure"},
{"name": "Reflect"},
{"name": "Magnet"},
{"name": "Fira"},
{"name": "Blizzara"},
{"name": "Thundara"},
{"name": "Cura"},
{"name": "Reflera"},
{"name": "Magnera"},
{"name": "Firaga"},
{"name": "Blizzaga"},
{"name": "Thundaga"},
{"name": "Curaga"},
{"name": "Reflega"},
{"name": "Magnega"},
{"name": "Second Chance"},
{"name": "Once More"},
{"name": "1 Torn Page"},
{"name": "2 Torn Pages"},
{"name": "3 Torn Pages"},
{"name": "4 Torn Pages"},
{"name": "5 Torn Pages"},
{"name": "Chicken Little"},
{"name": "Stitch"},
{"name": "Genie"},
{"name": "Peter Pan"},
{"name": "Proof of Nonexistence"},
{"name": "Proof of Peace"},
{"name": "Proof of Connection"},
{"name": "Promise Charm"},
{"name": "Beast's Claw"},
{"name": "Bone Fist"},
{"name": "Proud Fang"},
{"name": "Battlefields of War"},
{"name": "Sword of the Ancestor"},
{"name": "Skill and Crossbones"},
{"name": "Scimitar"},
{"name": "Identity Disk"},
{"name": "Membership Card"},
{"name": "Picture"},
{"name": "Ice Cream"},
{"name": "Hades Cup Trophy"},
{"name": "Unknown Disk"}]

var bossRandoList = 
[{"name": "7 keyblades"},
{"name": "7 unique staffs"},
{"name": "7 unique shields"},
{"name": "7 unique armors"},
{"name": "7 unique accessories"},
{"name": "10000 Munny"},
{"name": "Have 20 AP Boosts in your inventory"},
{"name": "Have 30 Potions in your inventory"},
{"name": "Have 1 of every magic element"},
{"name": "Use a tent"},
{"name": "Use one of any mega item"},
{"name": "Report 1, 2, or 3"},
{"name": "Report 4, 5, or 6"},
{"name": "Report 10, 11, 12, or 13"},
{"name": "Activate Anti-Form 13 times"},
{"name": "Use an auto form"},
{"name": "Use every limit in Limit Form once"},
{"name": "Valor Level 2"},
{"name": "Valor Level 3"},
{"name": "Valor Level 4"},
{"name": "Valor Level 5"},
{"name": "Valor Level 6"},
{"name": "Valor Level 7"},
{"name": "Wisdom Level 2"},
{"name": "Wisdom Level 3"},
{"name": "Wisdom Level 4"},
{"name": "Wisdom Level 5"},
{"name": "Wisdom Level 6"},
{"name": "Wisdom Level 7"},
{"name": "Limit Level 2"},
{"name": "Limit Level 3"},
{"name": "Limit Level 4"},
{"name": "Limit Level 5"},
{"name": "Limit Level 6"},
{"name": "Limit Level 7"},
{"name": "Master Level 2"},
{"name": "Master Level 3"},
{"name": "Master Level 4"},
{"name": "Master Level 5"},
{"name": "Master Level 6"},
{"name": "Master Level 7"},
{"name": "Final Level 2"},
{"name": "Final Level 3"},
{"name": "Final Level 4"},
{"name": "Final Level 5"},
{"name": "Final Level 6"},
{"name": "Final Level 7"},
{"name": "Level 20"},
{"name": "Level 25"},
{"name": "Level 30"},
{"name": "Level 35"},
{"name": "Level 40"},
{"name": "Level 45"},
{"name": "Level 50"},
{"name": "Summon Level 3"},
{"name": "Summon Level 4"},
{"name": "Summon Level 5"},
{"name": "Synth 3 Items"},
{"name": "Reach Moogle Level 2"},
{"name": "Collect all chests in Twilight Town"},
{"name": "Collect all chests in Hollow Bastion"},
{"name": "Collect all chests in Beast's Castle"},
{"name": "Collect all chests in Olympus Coliseum"},
{"name": "Collect all chests in Agrabah"},
{"name": "Collect all chests in Land of Dragons"},
{"name": "Collect all chests in 100 Acre Wood"},
{"name": "Collect all chests in Pride Lands"},
{"name": "Collect all chests in Disney Castle"},
{"name": "Collect all chests in Timeless River"},
{"name": "Collect all chests in Halloween Town"},
{"name": "Collect all chests in Port Royal"},
{"name": "Collect all chests in Space Paranoids"},
{"name": "Mail Delivery job"},
{"name": "Poster Duty job"},
{"name": "Cargo Climb job"},
{"name": "Grandstander job"},
{"name": "Bumble Buster job"},
{"name": "Junk Sweep job"},
{"name": "Use capsule prize on a Bulky Vendor"},
{"name": "Atlantica tutorial"},
{"name": "Buy something from Elmina (TT Moogle)"},
{"name": "Buy something from Mog (HB Moogle)"},
{"name": "Buy something form Kupo (LOD Moogle)"},
{"name": "Buy something form Monty (BC Moogle)"},
{"name": "Buy something from Mosh (OC Moogle)"},
{"name": "Buy something from Mogjiro (DC Moogle)"},
{"name": "Buy something from Mogtaro (TR Moogle)"},
{"name": "Buy something from Morlock (PR Moogle)"},
{"name": "Buy something from Gumo (HT Moogle)"},
{"name": "Buy something from Mojito (AG Moogle)"},
{"name": "Buy something from Kumop (PL Moogle)"},
{"name": "Buy something from Artemicion (SP Moogle)"},
{"name": "Buy something from Stiltzkin (TWTNW Moogle)"},
{"name": "Use 7 different limits"},
{"name": "Use Beast's limit"},
{"name": "Use Mulan's limit"},
{"name": "Use Auron's limit"},
{"name": "Use Jack Sparrow's limit"},
{"name": "Use Aladdin's limit"},
{"name": "Use Jack Skellington's limit"},
{"name": "Use Simba's limit"},
{"name": "Use Tron's limit"},
{"name": "Use a summon limit"},
{"name": "Obtain a Struggle weapon"},
{"name": "Defeat Twilight Thorn's replacement"},
{"name": "Defeat Seifer in the back alley as Roxas"},
{"name": "Win the Struggle against Hayner's replacement"},
{"name": "Win the Struggle against Vivi's replacement"},
{"name": "Defeat Axel 1's replacement as Roxas"},
{"name": "Win the Struggle against Setzer's replacement"},
{"name": "Go to Sunset Hill as Roxas"},
{"name": "Enter Namine's Room as Roxas"},
{"name": "Defeat Axel 2's replacement as Roxas"},
{"name": "Destroy all tents in Shang's Camp"},
{"name": "Complete all of Shang's missions"},
{"name": "Complete the mountain climb in Land of Dragons"},
{"name": "Beat cave fight in LOD1"},
{"name": "Beat summit fight in LOD1"},
{"name": "Defeat Shan Yu's replacement"},
{"name": "Defeat Riku's replacement in LOD"},
{"name": "Go to Throne Room in LOD"},
{"name": "Defeat Storm Rider's replacement"},
{"name": "Beat Hades Escape"},
{"name": "Defeat Cerberus's replacement"},
{"name": "Complete Phil's urn training"},
{"name": "Beat Demyx in OC1"},
{"name": "Beat Pete's replacement in OC1"},
{"name": "Defeat Hydra's replacement"},
{"name": "Beat Hades Cup in OC2"},
{"name": "Auron's Statue check in OC2"},
{"name": "Defeat Hades's replacement"},
{"name": "Destroy the armor statues in the West Hall of Beast's Castle"},
{"name": "Defeat Thresholder's replacement"},
{"name": "Complete Cogsworth minigame"},
{"name": "Examine Beast's rose"},
{"name": "Defeat Dark Thorn's replacement"},
{"name": "Rumbling Rose check in BC2"},
{"name": "Defeat Xaldin's replacement in Beast's Castle"},
{"name": "Minnie Escort"},
{"name": "Defeat Old Pete's replacement"},
{"name": "Beat construction window in TR"},
{"name": "Beat Lilliput window in TR"},
{"name": "Beat fire window in TR"},
{"name": "Go to Mickey's house in TR"},
{"name": "Complete all windows in TR"},
{"name": "Defeat Boat Pete"},
{"name": "Defeat Future Pete's replacement"},
{"name": "Beat 1min timed fight in PR1"},
{"name": "Beat an ambush on the boat in Port Royal"},
{"name": "Complete boat fight in PR1"},
{"name": "Beat barrels section in PR1"},
{"name": "Defeat Barbossa's replacement"},
{"name": "Defeat Grim Reaper 1's replacement"},
{"name": "Collect all medallions from the gamblers in PR2"},
{"name": "Defeat Grim Reaper 2's replacement"},
{"name": "Destroy a stall for a puzzle piece in Agrabah"},
{"name": "Jump on top of the Tiger Head in Agrabah"},
{"name": "Enter the Cave of Wonders"},
{"name": "Beat falling segment in AG1"},
{"name": "Open both treasures in the Treasure Room in Agrabah"},
{"name": "Defeat Twin Lords  replacements"},
{"name": "Ride on the Carpet in Agrabah"},
{"name": "Grab all 3 puzzle pieces in the Sandswept Ruins"},
{"name": "Open both treasures in the ruined chamber in Agrabah"},
{"name": "Defeat Genie Jafar"},
{"name": "Spin the carousel in Xmas Town"},
{"name": "Defeat Prison Keeper's replacement"},
{"name": "Defeat Oogie Boogie"},
{"name": "Beat Lock, Shock, and Barrel in the present factory"},
{"name": "Beat the Present minigame in Xmas Town"},
{"name": "Defeat the Experiment's replacement"},
{"name": "Talk to Rafiki"},
{"name": "Beat the Hyenas in PL1"},
{"name": "Defeat Scar's replacement"},
{"name": "Beat the Hyenas in PL2"},
{"name": "Defeat Groundshaker"},
{"name": "Beat the cube minigame in SP1"},
{"name": "Complete Light Cycle minigame"},
{"name": "Complete screens in SP1"},
{"name": "Defeat Hostile Program's replacement"},
{"name": "Beat light cycle fight in SP2"},
{"name": "Beat 2nd forced fight (w/ Devastators) in SP2"},
{"name": "Defeat Solar Sailer Heartless"},
{"name": "Defeat Sark's replacement"},
{"name": "Defeat MCP"},
{"name": "Talk to Scrooge"},
{"name": "Buy something from Huey Duck"},
{"name": "Buy something from Dewey Duck"},
{"name": "Buy something from Louie Duck"},
{"name": "Beat Bailey fight in HB"},
{"name": "Reach Ansem's study in Hollow Bastion"},
{"name": "Open Tifa's chest in Hollow Bastion"},
{"name": "Defeat Demyx's replacement in HB"},
{"name": "Fight with Yuffie in HB and win"},
{"name": "Fight with Tifa in HB and win"},
{"name": "Fight with Cloud in HB and win"},
{"name": "Beat 1k"},
{"name": "Open the Gull Wing chest in HB"},
{"name": "Enter Yen Sid's Tower"},
{"name": "Speak to the fairies at Yen Sid's Tower"},
{"name": "Beat sandlot fight in TT2"},
{"name": "Beat mansion fight in TT3"},
{"name": "Grab the puzzle piece in the pod room in TT"},
{"name": "Beat the Betwixt and Between fight"},
{"name": "Defeat Hayner's replacement as Sora"},
{"name": "Jump on top of a tram in Twilight Town"},
{"name": "Grab both puzzle pieces on Sunset Hill"},
{"name": "Examine the truck in TWTNW"},
{"name": "Proof of Existence"},
{"name": "Defeat Roxas's replacement in TWTNW"},
{"name": "Defeat Xigbar's replacement in TWTNW"},
{"name": "Defeat Luxord's replacement in TWTNW"},
{"name": "Defeat Saix's replacement in TWTNW"},
{"name": "Defeat Xemnas's replacement in TWTNW"},
{"name": "Save Piglet"},
{"name": "Reach the bottom of Honey Pot Hill"},
{"name": "Beat Balloon Bounce with Tigger and Roo"},
{"name": "Find Pooh in the Spooky Cave"},
{"name": "Yeet the Bear"},
{"name": "Examine Rabbit's clothesline"},
{"name": "Take Roxas's keyblades"},
{"name": "Play a game with Luxord"},
{"name": "Witness Saix enter his berserk state"},
{"name": "Examine one of Namine's drawings"},
{"name": "Touch the beam in Twilight Town"},
{"name": "Turn one portal pink"},
{"name": "Obtain Beast as a party member"},
{"name": "Obtain Jack Skellington as a party member"},
{"name": "Obtain Simba as a party member"},
{"name": "Obtain Jack Sparrow as a party member"},
{"name": "Obtain Riku as a party member"},
{"name": "Obtain Aladdin as a party member"},
{"name": "Obtain Auron as a party member"},
{"name": "Obtain Mulan as a party member"},
{"name": "Collect 10 puzzle pieces"},
{"name": "Collect 20 puzzle pieces"},
{"name": "Collect 30 puzzle pieces"},
{"name": "Collect 40 puzzle pieces"},
{"name": "Collect 50 puzzle pieces"},
{"name": "Complete 1 Puzzle"},
{"name": "Complete 2 Puzzles"},
{"name": "Complete Awakening Puzzle"},
{"name": "Complete Heart Puzzle"},
{"name": "Complete Duality Puzzle"},
{"name": "Complete Frontier Puzzle"},
{"name": "Complete Daylight Puzzle"},
{"name": "Complete Sunset Puzzle"},
{"name": "Collect 2 Puzzle Pieces in Triton's Throne"},
{"name": "Finny Fun"},
{"name": "Part of Your World"},
{"name": "Under the Sea"},
{"name": "Ursula's Revenge"},
{"name": "A New Day is Dawning"},
{"name": "Shroom 1 (TWTNW)"},
{"name": "Shroom 2 (Halloween Town)"},
{"name": "Shroom 3 (Beast's Castle)"},
{"name": "Shroom 4 (Land of Dragons)"},
{"name": "Shroom 5 (Agrabah)"},
{"name": "Shroom 6 (Olympus Coliseum)"},
{"name": "Shroom 7 (Twilight Town Tunnelway)"},
{"name": "Shroom 8 (Yen Sid's Tower)"},
{"name": "Shroom 9 (Hollow Bastion)"},
{"name": "Shroom 10 (Port Royal)"},
{"name": "Shroom 11 (Timeless River)"},
{"name": "Shroom 12 (Twilight Town Mansion)"},
{"name": "Shroom 13 (Proof of Peace Check)"},
{"name": "Beat Pain and Panic Cup"},
{"name": "Beat Cerberus Cup"},
{"name": "Beat Titan Cup"},
{"name": "Beat Goddess of Fate Cup"},
{"name": "Beat the 1st CoR fight"},
{"name": "Turn the valves in CoR"},
{"name": "Beat the 2nd CoR fight"},
{"name": "Get to the Engine Chamber in CoR"},
{"name": "Open the last chest in CoR"},
{"name": "Beat Transport to Remembrance"},
{"name": "Defeat AS Zexion's replacement"},
{"name": "Defeat AS Larxene's replacement"},
{"name": "Defeat AS Vexen's replacement"},
{"name": "Defeat AS Lexaeus's replacement"},
{"name": "Defeat AS Marluxia's replacement"},
{"name": "Defeat Data Roxas's replacement"},
{"name": "Defeat Data Demyx's replacement"},
{"name": "Defeat Data Zexion's replacement"},
{"name": "Defeat Data Xigbar's replacement"},
{"name": "Defeat Data Saix's replacement"},
{"name": "Defeat Data Vexen's replacement"},
{"name": "Defeat Data Larxene's replacement"},
{"name": "Defeat Data Axel's replacement"},
{"name": "Defeat Data Xaldin's replacement"},
{"name": "Defeat Data Lexaeus's replacement"},
{"name": "Defeat Data Marluxia's replacement"},
{"name": "Defeat Data Luxord's replacement"},
{"name": "Defeat Data Xemnas's replacement"},
{"name": "Defeat Sephiroth's replacement"},
{"name": "Defeat Terra's replacement"},
{"name": "Score 500 on SB Street Rave (Twilight Town)"},
{"name": "Score 100 on SB Freestyle (Hollow Bastion)"},
{"name": "Finish in 60s on SB Time Attack (Port Royal)"},
{"name": "Get 10 Crystals in 60s on SB Sand Slider (Agrabah)"},
{"name": "Score 500 on SB Workshop Rave (Halloween Town)"},
{"name": "Clash with Xemnas"},
{"name": "Enter the Laser Dome"},
{"name": "Use all of Genie's Limits"},
{"name": "Dual Wield Oathkeeper and Oblivion"},
{"name": "Obtain a -ga spell"},
{"name": "Bronze Crown"},
{"name": "Silver Crown"},
{"name": "Gold Crown"},
{"name": "Defeat Final Xemnas's replacement"},
{"name": "Obtain 3 Recipes"},
{"name": "Synth 1 Recipe Item"},
{"name": "Fire"},
{"name": "Blizzard"},
{"name": "Thunder"},
{"name": "Cure"},
{"name": "Reflect"},
{"name": "Magnet"},
{"name": "Fira"},
{"name": "Blizzara"},
{"name": "Thundara"},
{"name": "Cura"},
{"name": "Reflera"},
{"name": "Magnera"},
{"name": "Firaga"},
{"name": "Blizzaga"},
{"name": "Thundaga"},
{"name": "Curaga"},
{"name": "Reflega"},
{"name": "Magnega"},
{"name": "Second Chance"},
{"name": "Once More"},
{"name": "1 Torn Page"},
{"name": "2 Torn Pages"},
{"name": "3 Torn Pages"},
{"name": "4 Torn Pages"},
{"name": "5 Torn Pages"},
{"name": "Chicken Little"},
{"name": "Stitch"},
{"name": "Genie"},
{"name": "Peter Pan"},
{"name": "Proof of Nonexistence"},
{"name": "Proof of Peace"},
{"name": "Proof of Connection"},
{"name": "Promise Charm"},
{"name": "Beast's Claw"},
{"name": "Bone Fist"},
{"name": "Proud Fang"},
{"name": "Battlefields of War"},
{"name": "Sword of the Ancestor"},
{"name": "Skill and Crossbones"},
{"name": "Scimitar"},
{"name": "Identity Disk"},
{"name": "Membership Card"},
{"name": "Picture"},
{"name": "Ice Cream"},
{"name": "Hades Cup Trophy"},
{"name": "Unknown Disk"}]
