var masterGoalList = [
  { name: "7 keyblades" },
  { name: "7 unique staffs" },
  { name: "7 unique shields" },
  { name: "7 unique armors" },
  { name: "7 unique accessories" },
  { name: "10000 Munny" },
  { name: "Have 20 AP Boosts in your inventory" },
  { name: "Have 30 Potions in your inventory" },
  { name: "Have 1 of every magic element" },
  { name: "Use a tent" },
  { name: "Use one of any mega item" },
  { name: "Report 1, 2, or 3" },
  { name: "Report 4, 5, or 6" },
  { name: "Report 10, 11, 12, or 13" },
  { name: "Activate Anti-Form 13 times" },
  { name: "Use an auto form" },
  { name: "Use every limit in Limit Form once" },
  { name: "Valor Level 2" },
  { name: "Valor Level 3" },
  { name: "Valor Level 4" },
  { name: "Valor Level 5" },
  { name: "Valor Level 6" },
  { name: "Valor Level 7" },
  { name: "Wisdom Level 2" },
  { name: "Wisdom Level 3" },
  { name: "Wisdom Level 4" },
  { name: "Wisdom Level 5" },
  { name: "Wisdom Level 6" },
  { name: "Wisdom Level 7" },
  { name: "Limit Level 2" },
  { name: "Limit Level 3" },
  { name: "Limit Level 4" },
  { name: "Limit Level 5" },
  { name: "Limit Level 6" },
  { name: "Limit Level 7" },
  { name: "Master Level 2" },
  { name: "Master Level 3" },
  { name: "Master Level 4" },
  { name: "Master Level 5" },
  { name: "Master Level 6" },
  { name: "Master Level 7" },
  { name: "Final Level 2" },
  { name: "Final Level 3" },
  { name: "Final Level 4" },
  { name: "Final Level 5" },
  { name: "Final Level 6" },
  { name: "Final Level 7" },
  { name: "Level 20" },
  { name: "Level 25" },
  { name: "Level 30" },
  { name: "Level 35" },
  { name: "Level 40" },
  { name: "Level 45" },
  { name: "Level 50" },
  { name: "Summon Level 3" },
  { name: "Summon Level 4" },
  { name: "Summon Level 5" },
  { name: "Synth 3 Items" },
  { name: "Reach Moogle Level 2" },
  { name: "Collect all chests in Twilight Town" },
  { name: "Collect all chests in Hollow Bastion" },
  { name: "Collect all chests in Beast's Castle" },
  { name: "Collect all chests in Olympus Coliseum" },
  { name: "Collect all chests in Agrabah" },
  { name: "Collect all chests in Land of Dragons" },
  { name: "Collect all chests in 100 Acre Wood" },
  { name: "Collect all chests in Pride Lands" },
  { name: "Collect all chests in Disney Castle" },
  { name: "Collect all chests in Timeless River" },
  { name: "Collect all chests in Halloween Town" },
  { name: "Collect all chests in Port Royal" },
  { name: "Collect all chests in Space Paranoids" },
  { name: "Mail Delivery job" },
  { name: "Poster Duty job" },
  { name: "Cargo Climb job" },
  { name: "Grandstander job" },
  { name: "Bumble Buster job" },
  { name: "Junk Sweep job" },
  { name: "Use capsule prize on a Bulky Vendor" },
  { name: "Atlantica tutorial" },
  { name: "Buy something from Elmina (TT Moogle)" },
  { name: "Buy something from Mog (HB Moogle)" },
  { name: "Buy something form Kupo (LOD Moogle)" },
  { name: "Buy something form Monty (BC Moogle)" },
  { name: "Buy something from Mosh (OC Moogle)" },
  { name: "Buy something from Mogjiro (DC Moogle)" },
  { name: "Buy something from Mogtaro (TR Moogle)" },
  { name: "Buy something from Morlock (PR Moogle)" },
  { name: "Buy something from Gumo (HT Moogle)" },
  { name: "Buy something from Mojito (AG Moogle)" },
  { name: "Buy something from Kumop (PL Moogle)" },
  { name: "Buy something from Artemicion (SP Moogle)" },
  { name: "Buy something from Stiltzkin (TWTNW Moogle)" },
  { name: "Use 7 different limits" },
  { name: "Use Beast's limit" },
  { name: "Use Mulan's limit" },
  { name: "Use Auron's limit" },
  { name: "Use Jack Sparrow's limit" },
  { name: "Use Aladdin's limit" },
  { name: "Use Jack Skellington's limit" },
  { name: "Use Simba's limit" },
  { name: "Use Tron's limit" },
  { name: "Use a summon limit" },
  { name: "Obtain a Struggle weapon" },
  { name: "Defeat Twilight Thorn" },
  { name: "Defeat Seifer in the back alley as Roxas" },
  { name: "Win the Struggle against Hayner" },
  { name: "Win the Struggle against Vivi" },
  { name: "Defeat Axel 1 as Roxas" },
  { name: "Win the Struggle against Setzer" },
  { name: "Go to Sunset Hill as Roxas" },
  { name: "Enter Namine's Room as Roxas" },
  { name: "Defeat Axel 2 as Roxas" },
  { name: "Destroy all tents in Shang's Camp" },
  { name: "Complete all of Shang's missions" },
  { name: "Complete the mountain climb in Land of Dragons" },
  { name: "Beat cave fight in LOD1" },
  { name: "Beat summit fight in LOD1" },
  { name: "Defeat Shan Yu" },
  { name: "Defeat Riku in LOD" },
  { name: "Go to Throne Room in LOD" },
  { name: "Defeat Storm Rider" },
  { name: "Beat Hades Escape" },
  { name: "Defeat Cerberus" },
  { name: "Complete Phil's urn training" },
  { name: "Beat Demyx in OC1" },
  { name: "Beat Pete in OC1" },
  { name: "Defeat Hydra" },
  { name: "Beat Hades Cup in OC2" },
  { name: "Auron's Statue check in OC2" },
  { name: "Defeat Hades" },
  { name: "Destroy the armor statues in the West Hall of Beast's Castle" },
  { name: "Defeat Thresholder" },
  { name: "Complete Cogsworth minigame" },
  { name: "Examine Beast's rose" },
  { name: "Defeat Dark Thorn" },
  { name: "Rumbling Rose check in BC2" },
  { name: "Defeat Xaldin in Beast's Castle" },
  { name: "Minnie Escort" },
  { name: "Defeat Old Pete" },
  { name: "Beat construction window in TR" },
  { name: "Beat Lilliput window in TR" },
  { name: "Beat fire window in TR" },
  { name: "Go to Mickey's house in TR" },
  { name: "Complete all windows in TR" },
  { name: "Defeat Boat Pete" },
  { name: "Defeat Future Pete" },
  { name: "Beat 1min timed fight in PR1" },
  { name: "Beat an ambush on the boat in Port Royal" },
  { name: "Complete boat fight in PR1" },
  { name: "Beat barrels section in PR1" },
  { name: "Defeat Barbossa" },
  { name: "Defeat Grim Reaper 1" },
  { name: "Collect all medallions from the gamblers in PR2" },
  { name: "Defeat Grim Reaper 2" },
  { name: "Destroy a stall for a puzzle piece in Agrabah" },
  { name: "Jump on top of the Tiger Head in Agrabah" },
  { name: "Enter the Cave of Wonders" },
  { name: "Beat falling segment in AG1" },
  { name: "Open both treasures in the Treasure Room in Agrabah" },
  { name: "Defeat Twin Lords" },
  { name: "Ride on the Carpet in Agrabah" },
  { name: "Grab all 3 puzzle pieces in the Sandswept Ruins" },
  { name: "Open both treasures in the ruined chamber in Agrabah" },
  { name: "Defeat Genie Jafar" },
  { name: "Spin the carousel in Xmas Town" },
  { name: "Defeat Prison Keeper" },
  { name: "Defeat Oogie Boogie" },
  { name: "Beat Lock, Shock, and Barrel in the present factory" },
  { name: "Beat the Present minigame in Xmas Town" },
  { name: "Defeat the Experiment" },
  { name: "Talk to Rafiki" },
  { name: "Beat the Hyenas in PL1" },
  { name: "Defeat Scar" },
  { name: "Beat the Hyenas in PL2" },
  { name: "Defeat Groundshaker" },
  { name: "Beat the cube minigame in SP1" },
  { name: "Complete Light Cycle minigame" },
  { name: "Complete screens in SP1" },
  { name: "Defeat Hostile Program" },
  { name: "Beat light cycle fight in SP2" },
  { name: "Beat 2nd forced fight (w/ Devastators) in SP2" },
  { name: "Defeat Solar Sailer Heartless" },
  { name: "Defeat Sark" },
  { name: "Defeat MCP" },
  { name: "Talk to Scrooge" },
  { name: "Buy something from Huey Duck" },
  { name: "Buy something from Dewey Duck" },
  { name: "Buy something from Louie Duck" },
  { name: "Beat Bailey fight in HB" },
  { name: "Reach Ansem's study in Hollow Bastion" },
  { name: "Open Tifa's chest in Hollow Bastion" },
  { name: "Defeat Demyx in HB" },
  { name: "Fight with Yuffie in HB and win" },
  { name: "Fight with Tifa in HB and win" },
  { name: "Fight with Cloud in HB and win" },
  { name: "Beat 1k" },
  { name: "Open the Gull Wing chest in HB" },
  { name: "Enter Yen Sid's Tower" },
  { name: "Speak to the fairies at Yen Sid's Tower" },
  { name: "Beat sandlot fight in TT2" },
  { name: "Beat mansion fight in TT3" },
  { name: "Grab the puzzle piece in the pod room in TT" },
  { name: "Beat the Betwixt and Between fight" },
  { name: "Defeat Hayner as Sora" },
  { name: "Jump on top of a tram in Twilight Town" },
  { name: "Grab both puzzle pieces on Sunset Hill" },
  { name: "Examine the truck in TWTNW" },
  { name: "Proof of Existence" },
  { name: "Defeat Roxas in TWTNW" },
  { name: "Defeat Xigbar in TWTNW" },
  { name: "Defeat Luxord in TWTNW" },
  { name: "Defeat Saix in TWTNW" },
  { name: "Defeat Xemnas in TWTNW" },
  { name: "Save Piglet" },
  { name: "Reach the bottom of Honey Pot Hill" },
  { name: "Beat Balloon Bounce with Tigger and Roo" },
  { name: "Find Pooh in the Spooky Cave" },
  { name: "Yeet the Bear" },
  { name: "Examine Rabbit's clothesline" },
  { name: "Take Roxas's keyblades" },
  { name: "Play a game with Luxord" },
  { name: "Witness Saix enter his berserk state" },
  { name: "Examine one of Namine's drawings" },
  { name: "Touch the beam in Twilight Town" },
  { name: "Turn one portal pink" },
  { name: "Obtain Beast as a party member" },
  { name: "Obtain Jack Skellington as a party member" },
  { name: "Obtain Simba as a party member" },
  { name: "Obtain Jack Sparrow as a party member" },
  { name: "Obtain Riku as a party member" },
  { name: "Obtain Aladdin as a party member" },
  { name: "Obtain Auron as a party member" },
  { name: "Obtain Mulan as a party member" },
  { name: "Collect 10 puzzle pieces" },
  { name: "Collect 20 puzzle pieces" },
  { name: "Collect 30 puzzle pieces" },
  { name: "Collect 40 puzzle pieces" },
  { name: "Collect 50 puzzle pieces" },
  { name: "Complete 1 Puzzle" },
  { name: "Complete 2 Puzzles" },
  { name: "Complete Awakening Puzzle" },
  { name: "Complete Heart Puzzle" },
  { name: "Complete Duality Puzzle" },
  { name: "Complete Frontier Puzzle" },
  { name: "Complete Daylight Puzzle" },
  { name: "Complete Sunset Puzzle" },
  { name: "Collect 2 Puzzle Pieces in Triton's Throne" },
  { name: "Finny Fun" },
  { name: "Part of Your World" },
  { name: "Under the Sea" },
  { name: "Ursula's Revenge" },
  { name: "A New Day is Dawning" },
  { name: "Shroom 1 (TWTNW)" },
  { name: "Shroom 2 (Halloween Town)" },
  { name: "Shroom 3 (Beast's Castle)" },
  { name: "Shroom 4 (Land of Dragons)" },
  { name: "Shroom 5 (Agrabah)" },
  { name: "Shroom 6 (Olympus Coliseum)" },
  { name: "Shroom 7 (Twilight Town Tunnelway)" },
  { name: "Shroom 8 (Yen Sid's Tower)" },
  { name: "Shroom 9 (Hollow Bastion)" },
  { name: "Shroom 10 (Port Royal)" },
  { name: "Shroom 11 (Timeless River)" },
  { name: "Shroom 12 (Twilight Town Mansion)" },
  { name: "Shroom 13 (Proof of Peace Check)" },
  { name: "Beat Pain and Panic Cup" },
  { name: "Beat Cerberus Cup" },
  { name: "Beat Titan Cup" },
  { name: "Beat Goddess of Fate Cup" },
  { name: "Beat the 1st CoR fight" },
  { name: "Turn the valves in CoR" },
  { name: "Beat the 2nd CoR fight" },
  { name: "Get to the Engine Chamber in CoR" },
  { name: "Open the last chest in CoR" },
  { name: "Beat Transport to Remembrance" },
  { name: "Defeat AS Zexion" },
  { name: "Defeat AS Larxene" },
  { name: "Defeat AS Vexen" },
  { name: "Defeat AS Lexaeus" },
  { name: "Defeat AS Marluxia" },
  { name: "Defeat Data Roxas" },
  { name: "Defeat Data Demyx" },
  { name: "Defeat Data Zexion" },
  { name: "Defeat Data Xigbar" },
  { name: "Defeat Data Saix" },
  { name: "Defeat Data Vexen" },
  { name: "Defeat Data Larxene" },
  { name: "Defeat Data Axel" },
  { name: "Defeat Data Xaldin" },
  { name: "Defeat Data Lexaeus" },
  { name: "Defeat Data Marluxia" },
  { name: "Defeat Data Luxord" },
  { name: "Defeat Data Xemnas" },
  { name: "Defeat Sephiroth" },
  { name: "Defeat Terra" },
  { name: "Score 500 on SB Street Rave (Twilight Town)" },
  { name: "Score 100 on SB Freestyle (Hollow Bastion)" },
  { name: "Finish in 60s on SB Time Attack (Port Royal)" },
  { name: "Get 10 Crystals in 60s on SB Sand Slider (Agrabah)" },
  { name: "Score 500 on SB Workshop Rave (Halloween Town)" },
  { name: "Clash with Xemnas" },
  { name: "Enter the Laser Dome" },
  { name: "Use all of Genie's Limits" },
  { name: "Dual Wield Oathkeeper and Oblivion" },
  { name: "Obtain a -ga spell" },
  { name: "Bronze Crown" },
  { name: "Silver Crown" },
  { name: "Gold Crown" },
  { name: "Defeat Final Xemnas" },
  { name: "Obtain 3 Recipes" },
  { name: "Synth 1 Recipe Item" },
  { name: "Fire" },
  { name: "Blizzard" },
  { name: "Thunder" },
  { name: "Cure" },
  { name: "Reflect" },
  { name: "Magnet" },
  { name: "Fira" },
  { name: "Blizzara" },
  { name: "Thundara" },
  { name: "Cura" },
  { name: "Reflera" },
  { name: "Magnera" },
  { name: "Firaga" },
  { name: "Blizzaga" },
  { name: "Thundaga" },
  { name: "Curaga" },
  { name: "Reflega" },
  { name: "Magnega" },
  { name: "Second Chance" },
  { name: "Once More" },
  { name: "1 Torn Page" },
  { name: "2 Torn Pages" },
  { name: "3 Torn Pages" },
  { name: "4 Torn Pages" },
  { name: "5 Torn Pages" },
  { name: "Chicken Little" },
  { name: "Stitch" },
  { name: "Genie" },
  { name: "Peter Pan" },
  { name: "Proof of Nonexistence" },
  { name: "Proof of Peace" },
  { name: "Proof of Connection" },
  { name: "Promise Charm" },
  { name: "Beast's Claw" },
  { name: "Bone Fist" },
  { name: "Proud Fang" },
  { name: "Battlefields of War" },
  { name: "Sword of the Ancestor" },
  { name: "Skill and Crossbones" },
  { name: "Scimitar" },
  { name: "Identity Disk" },
  { name: "Membership Card" },
  { name: "Picture" },
  { name: "Ice Cream" },
  { name: "Hades Cup Trophy" },
  { name: "Unknown Disk" },
];

var bossRandoList = [
  { name: "7 keyblades" },
  { name: "7 unique staffs" },
  { name: "7 unique shields" },
  { name: "7 unique armors" },
  { name: "7 unique accessories" },
  { name: "10000 Munny" },
  { name: "Have 20 AP Boosts in your inventory" },
  { name: "Have 30 Potions in your inventory" },
  { name: "Have 1 of every magic element" },
  { name: "Use a tent" },
  { name: "Use one of any mega item" },
  { name: "Report 1, 2, or 3" },
  { name: "Report 4, 5, or 6" },
  { name: "Report 10, 11, 12, or 13" },
  { name: "Activate Anti-Form 13 times" },
  { name: "Use an auto form" },
  { name: "Use every limit in Limit Form once" },
  { name: "Valor Level 2" },
  { name: "Valor Level 3" },
  { name: "Valor Level 4" },
  { name: "Valor Level 5" },
  { name: "Valor Level 6" },
  { name: "Valor Level 7" },
  { name: "Wisdom Level 2" },
  { name: "Wisdom Level 3" },
  { name: "Wisdom Level 4" },
  { name: "Wisdom Level 5" },
  { name: "Wisdom Level 6" },
  { name: "Wisdom Level 7" },
  { name: "Limit Level 2" },
  { name: "Limit Level 3" },
  { name: "Limit Level 4" },
  { name: "Limit Level 5" },
  { name: "Limit Level 6" },
  { name: "Limit Level 7" },
  { name: "Master Level 2" },
  { name: "Master Level 3" },
  { name: "Master Level 4" },
  { name: "Master Level 5" },
  { name: "Master Level 6" },
  { name: "Master Level 7" },
  { name: "Final Level 2" },
  { name: "Final Level 3" },
  { name: "Final Level 4" },
  { name: "Final Level 5" },
  { name: "Final Level 6" },
  { name: "Final Level 7" },
  { name: "Level 20" },
  { name: "Level 25" },
  { name: "Level 30" },
  { name: "Level 35" },
  { name: "Level 40" },
  { name: "Level 45" },
  { name: "Level 50" },
  { name: "Summon Level 3" },
  { name: "Summon Level 4" },
  { name: "Summon Level 5" },
  { name: "Synth 3 Items" },
  { name: "Reach Moogle Level 2" },
  { name: "Collect all chests in Twilight Town" },
  { name: "Collect all chests in Hollow Bastion" },
  { name: "Collect all chests in Beast's Castle" },
  { name: "Collect all chests in Olympus Coliseum" },
  { name: "Collect all chests in Agrabah" },
  { name: "Collect all chests in Land of Dragons" },
  { name: "Collect all chests in 100 Acre Wood" },
  { name: "Collect all chests in Pride Lands" },
  { name: "Collect all chests in Disney Castle" },
  { name: "Collect all chests in Timeless River" },
  { name: "Collect all chests in Halloween Town" },
  { name: "Collect all chests in Port Royal" },
  { name: "Collect all chests in Space Paranoids" },
  { name: "Mail Delivery job" },
  { name: "Poster Duty job" },
  { name: "Cargo Climb job" },
  { name: "Grandstander job" },
  { name: "Bumble Buster job" },
  { name: "Junk Sweep job" },
  { name: "Use capsule prize on a Bulky Vendor" },
  { name: "Atlantica tutorial" },
  { name: "Buy something from Elmina (TT Moogle)" },
  { name: "Buy something from Mog (HB Moogle)" },
  { name: "Buy something form Kupo (LOD Moogle)" },
  { name: "Buy something form Monty (BC Moogle)" },
  { name: "Buy something from Mosh (OC Moogle)" },
  { name: "Buy something from Mogjiro (DC Moogle)" },
  { name: "Buy something from Mogtaro (TR Moogle)" },
  { name: "Buy something from Morlock (PR Moogle)" },
  { name: "Buy something from Gumo (HT Moogle)" },
  { name: "Buy something from Mojito (AG Moogle)" },
  { name: "Buy something from Kumop (PL Moogle)" },
  { name: "Buy something from Artemicion (SP Moogle)" },
  { name: "Buy something from Stiltzkin (TWTNW Moogle)" },
  { name: "Use 7 different limits" },
  { name: "Use Beast's limit" },
  { name: "Use Mulan's limit" },
  { name: "Use Auron's limit" },
  { name: "Use Jack Sparrow's limit" },
  { name: "Use Aladdin's limit" },
  { name: "Use Jack Skellington's limit" },
  { name: "Use Simba's limit" },
  { name: "Use Tron's limit" },
  { name: "Use a summon limit" },
  { name: "Obtain a Struggle weapon" },
  { name: "Defeat Twilight Thorn's replacement" },
  { name: "Defeat Seifer in the back alley as Roxas" },
  { name: "Win the Struggle against Hayner's replacement" },
  { name: "Win the Struggle against Vivi's replacement" },
  { name: "Defeat Axel 1's replacement as Roxas" },
  { name: "Win the Struggle against Setzer's replacement" },
  { name: "Go to Sunset Hill as Roxas" },
  { name: "Enter Namine's Room as Roxas" },
  { name: "Defeat Axel 2's replacement as Roxas" },
  { name: "Destroy all tents in Shang's Camp" },
  { name: "Complete all of Shang's missions" },
  { name: "Complete the mountain climb in Land of Dragons" },
  { name: "Beat cave fight in LOD1" },
  { name: "Beat summit fight in LOD1" },
  { name: "Defeat Shan Yu's replacement" },
  { name: "Defeat Riku's replacement in LOD" },
  { name: "Go to Throne Room in LOD" },
  { name: "Defeat Storm Rider's replacement" },
  { name: "Beat Hades Escape" },
  { name: "Defeat Cerberus's replacement" },
  { name: "Complete Phil's urn training" },
  { name: "Beat Demyx in OC1" },
  { name: "Beat Pete's replacement in OC1" },
  { name: "Defeat Hydra's replacement" },
  { name: "Beat Hades Cup in OC2" },
  { name: "Auron's Statue check in OC2" },
  { name: "Defeat Hades's replacement" },
  { name: "Destroy the armor statues in the West Hall of Beast's Castle" },
  { name: "Defeat Thresholder's replacement" },
  { name: "Complete Cogsworth minigame" },
  { name: "Examine Beast's rose" },
  { name: "Defeat Dark Thorn's replacement" },
  { name: "Rumbling Rose check in BC2" },
  { name: "Defeat Xaldin's replacement in Beast's Castle" },
  { name: "Minnie Escort" },
  { name: "Defeat Old Pete's replacement" },
  { name: "Beat construction window in TR" },
  { name: "Beat Lilliput window in TR" },
  { name: "Beat fire window in TR" },
  { name: "Go to Mickey's house in TR" },
  { name: "Complete all windows in TR" },
  { name: "Defeat Boat Pete" },
  { name: "Defeat Future Pete's replacement" },
  { name: "Beat 1min timed fight in PR1" },
  { name: "Beat an ambush on the boat in Port Royal" },
  { name: "Complete boat fight in PR1" },
  { name: "Beat barrels section in PR1" },
  { name: "Defeat Barbossa's replacement" },
  { name: "Defeat Grim Reaper 1's replacement" },
  { name: "Collect all medallions from the gamblers in PR2" },
  { name: "Defeat Grim Reaper 2's replacement" },
  { name: "Destroy a stall for a puzzle piece in Agrabah" },
  { name: "Jump on top of the Tiger Head in Agrabah" },
  { name: "Enter the Cave of Wonders" },
  { name: "Beat falling segment in AG1" },
  { name: "Open both treasures in the Treasure Room in Agrabah" },
  { name: "Defeat Twin Lords  replacements" },
  { name: "Ride on the Carpet in Agrabah" },
  { name: "Grab all 3 puzzle pieces in the Sandswept Ruins" },
  { name: "Open both treasures in the ruined chamber in Agrabah" },
  { name: "Defeat Genie Jafar" },
  { name: "Spin the carousel in Xmas Town" },
  { name: "Defeat Prison Keeper's replacement" },
  { name: "Defeat Oogie Boogie" },
  { name: "Beat Lock, Shock, and Barrel in the present factory" },
  { name: "Beat the Present minigame in Xmas Town" },
  { name: "Defeat the Experiment's replacement" },
  { name: "Talk to Rafiki" },
  { name: "Beat the Hyenas in PL1" },
  { name: "Defeat Scar's replacement" },
  { name: "Beat the Hyenas in PL2" },
  { name: "Defeat Groundshaker" },
  { name: "Beat the cube minigame in SP1" },
  { name: "Complete Light Cycle minigame" },
  { name: "Complete screens in SP1" },
  { name: "Defeat Hostile Program's replacement" },
  { name: "Beat light cycle fight in SP2" },
  { name: "Beat 2nd forced fight (w/ Devastators) in SP2" },
  { name: "Defeat Solar Sailer Heartless" },
  { name: "Defeat Sark's replacement" },
  { name: "Defeat MCP" },
  { name: "Talk to Scrooge" },
  { name: "Buy something from Huey Duck" },
  { name: "Buy something from Dewey Duck" },
  { name: "Buy something from Louie Duck" },
  { name: "Beat Bailey fight in HB" },
  { name: "Reach Ansem's study in Hollow Bastion" },
  { name: "Open Tifa's chest in Hollow Bastion" },
  { name: "Defeat Demyx's replacement in HB" },
  { name: "Fight with Yuffie in HB and win" },
  { name: "Fight with Tifa in HB and win" },
  { name: "Fight with Cloud in HB and win" },
  { name: "Beat 1k" },
  { name: "Open the Gull Wing chest in HB" },
  { name: "Enter Yen Sid's Tower" },
  { name: "Speak to the fairies at Yen Sid's Tower" },
  { name: "Beat sandlot fight in TT2" },
  { name: "Beat mansion fight in TT3" },
  { name: "Grab the puzzle piece in the pod room in TT" },
  { name: "Beat the Betwixt and Between fight" },
  { name: "Defeat Hayner's replacement as Sora" },
  { name: "Jump on top of a tram in Twilight Town" },
  { name: "Grab both puzzle pieces on Sunset Hill" },
  { name: "Examine the truck in TWTNW" },
  { name: "Proof of Existence" },
  { name: "Defeat Roxas's replacement in TWTNW" },
  { name: "Defeat Xigbar's replacement in TWTNW" },
  { name: "Defeat Luxord's replacement in TWTNW" },
  { name: "Defeat Saix's replacement in TWTNW" },
  { name: "Defeat Xemnas's replacement in TWTNW" },
  { name: "Save Piglet" },
  { name: "Reach the bottom of Honey Pot Hill" },
  { name: "Beat Balloon Bounce with Tigger and Roo" },
  { name: "Find Pooh in the Spooky Cave" },
  { name: "Yeet the Bear" },
  { name: "Examine Rabbit's clothesline" },
  { name: "Take Roxas's keyblades" },
  { name: "Play a game with Luxord" },
  { name: "Witness Saix enter his berserk state" },
  { name: "Examine one of Namine's drawings" },
  { name: "Touch the beam in Twilight Town" },
  { name: "Turn one portal pink" },
  { name: "Obtain Beast as a party member" },
  { name: "Obtain Jack Skellington as a party member" },
  { name: "Obtain Simba as a party member" },
  { name: "Obtain Jack Sparrow as a party member" },
  { name: "Obtain Riku as a party member" },
  { name: "Obtain Aladdin as a party member" },
  { name: "Obtain Auron as a party member" },
  { name: "Obtain Mulan as a party member" },
  { name: "Collect 10 puzzle pieces" },
  { name: "Collect 20 puzzle pieces" },
  { name: "Collect 30 puzzle pieces" },
  { name: "Collect 40 puzzle pieces" },
  { name: "Collect 50 puzzle pieces" },
  { name: "Complete 1 Puzzle" },
  { name: "Complete 2 Puzzles" },
  { name: "Complete Awakening Puzzle" },
  { name: "Complete Heart Puzzle" },
  { name: "Complete Duality Puzzle" },
  { name: "Complete Frontier Puzzle" },
  { name: "Complete Daylight Puzzle" },
  { name: "Complete Sunset Puzzle" },
  { name: "Collect 2 Puzzle Pieces in Triton's Throne" },
  { name: "Finny Fun" },
  { name: "Part of Your World" },
  { name: "Under the Sea" },
  { name: "Ursula's Revenge" },
  { name: "A New Day is Dawning" },
  { name: "Shroom 1 (TWTNW)" },
  { name: "Shroom 2 (Halloween Town)" },
  { name: "Shroom 3 (Beast's Castle)" },
  { name: "Shroom 4 (Land of Dragons)" },
  { name: "Shroom 5 (Agrabah)" },
  { name: "Shroom 6 (Olympus Coliseum)" },
  { name: "Shroom 7 (Twilight Town Tunnelway)" },
  { name: "Shroom 8 (Yen Sid's Tower)" },
  { name: "Shroom 9 (Hollow Bastion)" },
  { name: "Shroom 10 (Port Royal)" },
  { name: "Shroom 11 (Timeless River)" },
  { name: "Shroom 12 (Twilight Town Mansion)" },
  { name: "Shroom 13 (Proof of Peace Check)" },
  { name: "Beat Pain and Panic Cup" },
  { name: "Beat Cerberus Cup" },
  { name: "Beat Titan Cup" },
  { name: "Beat Goddess of Fate Cup" },
  { name: "Beat the 1st CoR fight" },
  { name: "Turn the valves in CoR" },
  { name: "Beat the 2nd CoR fight" },
  { name: "Get to the Engine Chamber in CoR" },
  { name: "Open the last chest in CoR" },
  { name: "Beat Transport to Remembrance" },
  { name: "Defeat AS Zexion's replacement" },
  { name: "Defeat AS Larxene's replacement" },
  { name: "Defeat AS Vexen's replacement" },
  { name: "Defeat AS Lexaeus's replacement" },
  { name: "Defeat AS Marluxia's replacement" },
  { name: "Defeat Data Roxas's replacement" },
  { name: "Defeat Data Demyx's replacement" },
  { name: "Defeat Data Zexion's replacement" },
  { name: "Defeat Data Xigbar's replacement" },
  { name: "Defeat Data Saix's replacement" },
  { name: "Defeat Data Vexen's replacement" },
  { name: "Defeat Data Larxene's replacement" },
  { name: "Defeat Data Axel's replacement" },
  { name: "Defeat Data Xaldin's replacement" },
  { name: "Defeat Data Lexaeus's replacement" },
  { name: "Defeat Data Marluxia's replacement" },
  { name: "Defeat Data Luxord's replacement" },
  { name: "Defeat Data Xemnas's replacement" },
  { name: "Defeat Sephiroth's replacement" },
  { name: "Defeat Terra's replacement" },
  { name: "Score 500 on SB Street Rave (Twilight Town)" },
  { name: "Score 100 on SB Freestyle (Hollow Bastion)" },
  { name: "Finish in 60s on SB Time Attack (Port Royal)" },
  { name: "Get 10 Crystals in 60s on SB Sand Slider (Agrabah)" },
  { name: "Score 500 on SB Workshop Rave (Halloween Town)" },
  { name: "Clash with Xemnas" },
  { name: "Enter the Laser Dome" },
  { name: "Use all of Genie's Limits" },
  { name: "Dual Wield Oathkeeper and Oblivion" },
  { name: "Obtain a -ga spell" },
  { name: "Bronze Crown" },
  { name: "Silver Crown" },
  { name: "Gold Crown" },
  { name: "Defeat Final Xemnas's replacement" },
  { name: "Obtain 3 Recipes" },
  { name: "Synth 1 Recipe Item" },
  { name: "Fire" },
  { name: "Blizzard" },
  { name: "Thunder" },
  { name: "Cure" },
  { name: "Reflect" },
  { name: "Magnet" },
  { name: "Fira" },
  { name: "Blizzara" },
  { name: "Thundara" },
  { name: "Cura" },
  { name: "Reflera" },
  { name: "Magnera" },
  { name: "Firaga" },
  { name: "Blizzaga" },
  { name: "Thundaga" },
  { name: "Curaga" },
  { name: "Reflega" },
  { name: "Magnega" },
  { name: "Second Chance" },
  { name: "Once More" },
  { name: "1 Torn Page" },
  { name: "2 Torn Pages" },
  { name: "3 Torn Pages" },
  { name: "4 Torn Pages" },
  { name: "5 Torn Pages" },
  { name: "Chicken Little" },
  { name: "Stitch" },
  { name: "Genie" },
  { name: "Peter Pan" },
  { name: "Proof of Nonexistence" },
  { name: "Proof of Peace" },
  { name: "Proof of Connection" },
  { name: "Promise Charm" },
  { name: "Beast's Claw" },
  { name: "Bone Fist" },
  { name: "Proud Fang" },
  { name: "Battlefields of War" },
  { name: "Sword of the Ancestor" },
  { name: "Skill and Crossbones" },
  { name: "Scimitar" },
  { name: "Identity Disk" },
  { name: "Membership Card" },
  { name: "Picture" },
  { name: "Ice Cream" },
  { name: "Hades Cup Trophy" },
  { name: "Unknown Disk" },
];

var bunterList = [
  { name: "Armor Xemnas 1" },
  { name: "Armor Xemnas 2" },
  { name: "Axel 1" },
  { name: "Axel 2" },
  { name: "Barbossa" },
  { name: "Blizzard Lord" },
  { name: "The Beast" },
  { name: "Cerberus" },
  { name: "Cloud" },
  { name: "Dark Thorn" },
  { name: "Demyx" },
  { name: "The Experiment" },
  { name: "Final Xemnas" },
  { name: "Grim Reaper 1" },
  { name: "Grim Reaper 2" },
  { name: "Groundshaker" },
  { name: "Hades" },
  { name: "Hayner" },
  { name: "Hercules" },
  { name: "Hostile Program" },
  { name: "Hydra" },
  { name: "Jafar" },
  { name: "Leon" },
  { name: "Luxord" },
  { name: "MCP" },
  { name: "Past Pete" },
  { name: "Oogie Boogie" },
  { name: "Pete TR" },
  { name: "Prison Keeper" },
  { name: "Riku" },
  { name: "Roxas" },
  { name: "Saix" },
  { name: "Sark" },
  { name: "Scar" },
  { name: "Seifer" },
  { name: "Setzer" },
  { name: "Shadow Stalker" },
  { name: "Shadow Roxas" },
  { name: "Shan-Yu" },
  { name: "Storm Rider" },
  { name: "Thresholder" },
  { name: "Tifa" },
  { name: "Twilight Thorn" },
  { name: "Vivi" },
  { name: "Volcano Lord" },
  { name: "Xaldin" },
  { name: "Xemnas" },
  { name: "Xigbar" },
  { name: "Yuffie" },
  //{ name: "Axel (Data)" },
  //{ name: "Demyx (Data)" },
  //{ name: "Final Xemnas (Data)" },
  { name: "Larxene" },
  //{ name: "Larxene (Data)" },
  { name: "Lexaeus" },
  //{ name: "Lexaeus (Data)" },
  //{ name: "Luxord (Data)" },
  { name: "Marluxia" },
  //{ name: "Marluxia (Data)" },
  //{ name: "Roxas (Data)" },
  //{ name: "Saix (Data)" },
  { name: "Sephiroth" },
  { name: "Terra" },
  { name: "Vexen" },
  //{ name: "Vexen (Data)" },
  //{ name: "Xaldin (Data)" },
  //{ name: "Xemnas (Data)" },
  //{ name: "Xigbar (Data)" },
  { name: "Zexion" },
  //{ name: "Zexion (Data)" },
];

var kh1goals = [
  { name: "Acquire All 5 Trinities" },
  { name: "Activate All Blue Trinities" },
  { name: "Activate All Yellow Trinities" },
  { name: "Activate All Green Trinities" },
  { name: "Activate All Red Trinities" },
  { name: "Activate All White Trinities" },
  { name: "Activate All Trinities in Traverse Town" },
  { name: "Activate All Trinities in Wonderland" },
  { name: "Activate All Trinities in Monstro" },
  { name: "Activate All Trinities in Olympus Coliseum" },
  { name: "Activate All Trinities in Deep Jungle" },
  { name: "Activate All Trinities in Agrabah" },
  { name: "Activate All Trinities in Hollow Bastion" },
  { name: "Activate All Trinities in Halloween Town" },
  { name: "Activate All Trinities in Neverland" },
  { name: "Acquire Blue Trinity" },
  { name: "Acquire Yellow Trinity" },
  { name: "Acquire White Trinity" },
  { name: "Acquire Red Trinity" },
  { name: "Acquire Green Trinity" },
  { name: "Seal 3 Keyholes" },
  { name: "Seal 5 Keyholes" },
  { name: "Seal 8 Keyholes" },
  { name: "Defeat any 1 Super Boss" },
  { name: "Defeat Kurt Zisa" },
  { name: "Defeat Phantom" },
  { name: "Defeat Ice Titan" },
  { name: "Clear Wonderland" },
  { name: "Clear Agrabah" },
  { name: "Clear Monstro" },
  { name: "Clear Neverland" },
  { name: "Clear Deep Jungle" },
  { name: "Clear Atlantica" },
  { name: "Clear Hollow Bastion" },
  { name: "Clear Halloween Town" },
  { name: "Obtain Ultima Weapon or Wooden Sword" },
  { name: "Obtain Metal Chocobo, Lionheart, or One-Winged Angel" },
  { name: "Obtain Dream Sword, Rod or Shield (Any Party Members)" },
  { name: "Obtain Oathkeeper or Oblivion" },
  { name: "Obtain Diamond Dust or One-Winged Angel" },
  { name: "Obtain Metal Chocobo or Lionheart" },
  { name: "Obtain Divine Rose or Ladyluck" },
  { name: "Obtain Three Wishes or Wishing Star" },
  { name: "Obtain Fairy Harp or Crabclaw" },
  { name: "Obtain Jungleking or Pumpkinhead" },
  { name: "Obtain Olympia or Spellbinder" },
  { name: "Possess 7 Unique Keyblades Simultaneously" },
  { name: "Possess 13 Unique Keyblades Simultaneously" },
  { name: "Clear Phil Cup" },
  { name: "Clear Phil Cup Time-Trial" },
  { name: "Clear Pegasus Cup" },
  { name: "Clear Pegasus Cup Time-Trial" },
  { name: "Clear Herc Cup" },
  { name: "Clear Herc Cup-Time Trial" },
  { name: "Clear Phil, Pegasus, and Herc Cup" },
  { name: "Clear Hades Cup 40th Seed (Behemoth)" },
  { name: "Clear Hades Cup 30th Seed (Cerberus)" },
  { name: "Clear Hades Cup 20th Seed (Cloud & Leon)" },
  { name: "Clear Hades Cup 10th Seed (Hades)" },
  { name: "Find 33 Puppies" },
  { name: "Find 66 Puppies" },
  { name: "Find 99 Puppies" },
  { name: "Possess All 13 Ansem Reports Simultaneously" },
  { name: "Reach 11 MP With Donald" },
  { name: "Reach 50 STR With Sora" },
  { name: "Reach 7 MP With Goofy" },
  { name: "Reach 10 MP With Sora" },
  { name: "Find 3 Post Cards" },
  { name: "Find 7 Post Cards" },
  { name: "Find 10 Post Cards" },
  { name: "Beat Riku In A Race" },
  { name: "15/20 Chests in Traverse Town" },
  { name: "15/19 Chests in Wonderland" },
  { name: "15/37 Chests in Agrabah" },
  { name: "20/25 Chests in End of the World" },
  { name: "15/19 Chests in Halloween Town" },
  { name: "25/37 Chests in Hollow Bastion" },
  { name: "5/10 Chests in World Terminus" },
  { name: "3/5 Chests in Olympus Coliseum" },
  { name: "All 20 Chests in Traverse Town" },
  { name: "All 19 Chests in Wonderland" },
  { name: "All 19 Chests in Deep Jungle" },
  { name: "All 6 Chests in Olympus Coliseum" },
  { name: "All 21 Chests in Cave of Wonders" },
  { name: "All 19 Chests in Halloween Town" },
  { name: "All 10 Chests in Neverland" },
  { name: "All 10 Chests in Final Dimension" },
  { name: "All 5 Chests in Giant Crevasse" },
  { name: "All 6 Chests in Monstro's Mouth" },
  { name: "Open a Clam 7 Times in Atlantica" },
  { name: "Ride in Lock, Shock, and Barrel's Bathtub" },
  { name: "Clear 100 Acre Woods" },
  { name: "Give Owl 5 Rare Nuts" },
  { name: "Don't Let Tigger Stomp a Single Carrot" },
  { name: "Don't Let Bees Pop Pooh's Balloon" },
  { name: "Send Pooh At Least 30m Off the Swing" },
  { name: "Lead Pooh to 3 Jars of Honey" },
  { name: "Pull Out all of Rabbit's Crops" },
  { name: "Blow up an Urchin in Atlantica" },
  { name: "Gather 50 Fruit on Jungle Slider" },
  { name: "Synth 6 Unique Items" },
  { name: "Synth 12 Unique Items" },
  { name: "Synth 18 Unique Items" },
  { name: "Sora: Ars or Strike Raid" },
  { name: "Sora: Leaf Bracer or Second Chance" },
  { name: "Sora: Sonic Blade or Ripple Drive" },
  { name: "Sora: Vortex or Hurricane Blast" },
  { name: "Sora: Scan-Ra" },
  { name: "Sora: MP Rage or MP Haste" },
  { name: "Sora: Tech Boost or Treasure Magnet" },
  { name: "Sora: Lucky Strike or Critical Plus" },
  { name: "2 Combo Plus" },
  { name: "Sora: Slapshot or Sliding Dash" },
  { name: "Sora: Zantetsuken or Stun Impact" },
  { name: "Sora: Gravity Break or Blitz" },
  { name: "Sora: Guard or Dodgeroll" },
  { name: "Sora: Combo-Master or Counter Attack" },
  { name: "50 Hits on a Rare Truffle" },
  { name: "100 Hits on a Rare Truffle" },
  { name: "Get Poisoned" },
  { name: "High Jump-Ga" },
  { name: "3 Unique Mushroom Arts" },
  { name: "5 Unique Mushroom Arts" },
  { name: "Collect the Seagull Egg Check on Day 2" },
  { name: "Collect a Coconut Check on Day 2" },
  { name: "Collect a Log check on Day 1" },
  { name: "Collect the Cloth check on Day 1" },
  { name: "Collect the Rope check on Day 1" },
  { name: "Collect a Fish check on Day 2" },
  { name: "Collect a Mushroom check on Day 2" },
  { name: "Fight the 3v1 on Destiny Islands" },
  { name: "Collect the Drinking Water Check on Day 2" },
  { name: "Learn the Spell Graviga" },
  { name: "Learn the Spell Aeroga" },
  { name: "Learn the Spell Firaga" },
  { name: "Learn the Spell Blizzaga" },
  { name: "Learn the Spell Stopga" },
  { name: "Learn the Spell Thundaga" },
  { name: "Learn the Spell Curaga" },
  { name: "1 Ga-Spell" },
  { name: "2 Ga-Spells" },
  { name: "3 Ga-Spells" },
  { name: "Replace all of the Books in the Library" },
  { name: "Show Merlin 7 Unique Spells (Spellbinder Check)" },
  { name: "Watch Merlin Dance" },
  { name: "Acquire Bambi" },
  { name: "Acquire Genie" },
  { name: "Acquire Mushu" },
  { name: "Acquire Dumbo" },
  { name: "Acquire Tinker Bell" },
  { name: "Acquire Simba" },
  { name: "All 6 Summons" },
  { name: "Finish the Prelims" },
  { name: "Reach Level 20" },
  { name: "Reach Level 30" },
  { name: "Reach Level 40" },
  { name: "Reach Level 50" },
  { name: "Kill a Grand Ghost" },
  { name: "Kill a Stealth Soldier" },
  { name: "Kill a Chimera" },
  { name: "Kill a Pot Scorpion" },
  { name: "Kill a Gigas Shadow" },
  { name: "Kill a Jet Balloon" },
  { name: "Kill 3 Unique Pureblood Heartless" },
  { name: "Kill 5 Unique Pureblood Heartless" },
  { name: "Defeat Oogie" },
  { name: "Defeat a Boss with Their World's Keyblade" },
  { name: "Defeat Anti-Sora" },
  { name: "Obtain the Elixir from Jack's House" },
  { name: "Defeat 150 of a Single Heartless" },
  { name: "Defeat 300 of a single Heartless" },
  { name: "Defeat Maleficent" },
  { name: "Defeat Dragon Maleficent" },
  { name: "Defeat a Behemoth" },
  { name: "Defeat 4 Behemoths" },
  { name: "Defeat Ursula" },
  { name: "Defeat Cloud with the Metal Chocobo or One-Winged Angel" },
  { name: "Defeat Cloud in the Herc Cup" },
  { name: "Defeat Yuffie in the Hades Cup" },
  { name: "Defeat Riku with Wooden Sword" },
  { name: "Defeat Riku in Entrance Hall" },
  { name: "Defeat Ansem-Riku in Grand Hall" },
  { name: "Blizzaga Chest in Olympus Coliseum" },
  { name: "Blizzara Chest in Olympus Coliseum" },
  { name: "Recieve an Item from Kairi in the Secret Waterway" },
  { name: "Obtain Superglide (any 2 Glides)" },
  { name: "Obtain High Jump" },
  { name: "3 Unique EXP Items" },
  { name: "Obtain an EXP Item" },
  { name: "Sora: Ars Arcanum or Ragnarok" },
  { name: "Obtain Glide (any 1 Glide)" },
  { name: "Sora: Obtain Trinity Limit" },
  { name: "Sora: Obtain Cheer" },
  { name: "Sora: Obtain Trinity Limit or Cheer" },
  { name: "Any Ra-Spell" },
  { name: "3 Ra-Spells" },
  { name: "5 Ra-Spells" },
  { name: "All Ra-Spells" },
  { name: "Talk to Belle in the Library" },
  { name: "Destiny Island Day 2 Chest" },
  { name: "Brew a Potion in Camp" },
  { name: "Collect a Clock Tower Door Reward" },
  { name: "Collect 2 Clock Tower Door Rewards" },
  { name: "Obtain Fire Arts" },
  { name: "Obtain Blizzard Arts" },
  { name: "Obtain Thunder Arts" },
  { name: "Obtain Cure Arts" },
  { name: "Obtain Stop Arts" },
  { name: "Obtain Gravity Arts" },
  { name: "Obtain Aero Arts" },
  { name: "At Least 50 Hits on Pink Agaricus" },
  { name: "Become a Heartless" },
  { name: "Open All Evidence Boxes" },
  { name: "Visit Geppetto's House" },
  { name: "Possess 15000 Munny Simultaneously" },
  { name: "Obtain the Cid Model Blueprint" },
  { name: "Obtain the Chocobo Model Blueprint" },
  { name: "Break all Pots without Waking Pot Scorpion" },
  { name: "Complete a Section of Jiminy's Journal" },
  { name: "Open the Emblem Door in Hollow Bastion" },
  { name: "Collect all 4 Emblem Piece Checks" },
  { name: "Flame Emblem Piece Check" },
  { name: "Chest Emblem Piece Check" },
  { name: "Fountain Emblem Piece Check" },
  { name: "Statue Emblem Piece Check" },
  { name: "Have all Day 1 Destiny Island Items" },
  { name: "Have all Day 2 Destiny Island Items" },
  { name: "Compete Against Riku 10 Times" },
  { name: "Sora: Obtain Air Combo Plus or Combo Plus" },
  { name: "Save Aladdin From the Sand" },
  { name: "Defeat Opposite Armor" },
  { name: "Defeat Cerberus" },
  { name: "Save Jane from the Heartless" },
  { name: "Green Trinity In Monstro" },
  { name: "All 4 Chests in the Cemetery" },
  { name: "Start A Fight in the Queens Courtyard" },
  { name: "Hitch a Ride with a Dolphin" },
  { name: "Defeat Parasite Cage for the First Time" },
  { name: "Defeat Parasite Cage for the Second Time" },
  { name: "All 4 Chests in Tea Party Garden" },
  { name: "Freeze a Bubble in Hollow Bastion" },
  { name: "Ride in 4 Different Bubbles in Hollow Bastion" },
  { name: "Have Beast Join Your Party" },
  { name: "Have Ariel Join Your Party" },
  { name: "Power the Gizmo Shop" },
  { name: "Blow out the Candles in First District" },
  { name: "Light the Fire Place in the Accessory Shop" },
  { name: "Acquire Jack-In-The-Box" },
  { name: "Acquire a Slide" },
  { name: "Acquire the Entry Pass" },
  { name: "Acquire Evidence" },
  { name: "Defeat Leon with The Lionheart" },
  { name: "Kill 10 Black Mushrooms" },
  { name: "Activate the White Trinity in Atlantica" },
  { name: "Defeat Trickmaster" },
  { name: "Defeat Sabor 2" },
  { name: "Defeat Clayton" },
  { name: "Defeat the Tiger Head" },
  { name: "Defeat the Pot Spider" },
  { name: "Defeat Genie Jafar" },
  { name: "Open all chests in Oogie Manor" },
  { name: "Defeat Captain Hook" },
  { name: "Activate the Yellow Trinity on Hook's Ship" },
  { name: "Open the clam at King Trident's Palace" },
  { name: "Defeat the shark in Atlantica" },
  { name: "Open the castle door in Hollow Bastion" },
];

var comboList = [
  { name: "KH2: 7 keyblades" },
  { name: "KH2: 7 unique staffs" },
  { name: "KH2: 7 unique shields" },
  { name: "KH2: 7 unique armors" },
  { name: "KH2: 7 unique accessories" },
  { name: "KH2: Have 1 of every magic element" },
  { name: "KH2: Use a tent" },
  { name: "KH2: Use one of any mega item" },
  { name: "KH2: Report 1, 2, or 3" },
  { name: "KH2: Report 4, 5, or 6" },
  { name: "KH2: Report 10, 11, 12, or 13" },
  { name: "KH2: Activate Anti-Form 13 times" },
  { name: "KH2: Use an auto form" },
  { name: "KH2: Use every limit in Limit Form once" },
  { name: "KH2: Valor Level 2" },
  { name: "KH2: Valor Level 3" },
  { name: "KH2: Valor Level 4" },
  { name: "KH2: Valor Level 5" },
  { name: "KH2: Valor Level 6" },
  { name: "KH2: Valor Level 7" },
  { name: "KH2: Wisdom Level 2" },
  { name: "KH2: Wisdom Level 3" },
  { name: "KH2: Wisdom Level 4" },
  { name: "KH2: Wisdom Level 5" },
  { name: "KH2: Wisdom Level 6" },
  { name: "KH2: Wisdom Level 7" },
  { name: "KH2: Limit Level 2" },
  { name: "KH2: Limit Level 3" },
  { name: "KH2: Limit Level 4" },
  { name: "KH2: Limit Level 5" },
  { name: "KH2: Limit Level 6" },
  { name: "KH2: Limit Level 7" },
  { name: "KH2: Master Level 2" },
  { name: "KH2: Master Level 3" },
  { name: "KH2: Master Level 4" },
  { name: "KH2: Master Level 5" },
  { name: "KH2: Master Level 6" },
  { name: "KH2: Master Level 7" },
  { name: "KH2: Final Level 2" },
  { name: "KH2: Final Level 3" },
  { name: "KH2: Final Level 4" },
  { name: "KH2: Final Level 5" },
  { name: "KH2: Final Level 6" },
  { name: "KH2: Final Level 7" },
  { name: "KH2: Level 20" },
  { name: "KH2: Level 25" },
  { name: "KH2: Level 30" },
  { name: "KH2: Level 35" },
  { name: "KH2: Level 40" },
  { name: "KH2: Level 45" },
  { name: "KH2: Level 50" },
  { name: "KH2: Collect all chests in Twilight Town" },
  { name: "KH2: Collect all chests in Hollow Bastion" },
  { name: "KH2: Collect all chests in Beast's Castle" },
  { name: "KH2: Collect all chests in Olympus Coliseum" },
  { name: "KH2: Collect all chests in Agrabah" },
  { name: "KH2: Collect all chests in Land of Dragons" },
  { name: "KH2: Collect all chests in 100 Acre Wood" },
  { name: "KH2: Collect all chests in Pride Lands" },
  { name: "KH2: Collect all chests in Disney Castle" },
  { name: "KH2: Collect all chests in Timeless River" },
  { name: "KH2: Collect all chests in Halloween Town" },
  { name: "KH2: Collect all chests in Port Royal" },
  { name: "KH2: Collect all chests in Space Paranoids" },
  { name: "KH2: Use capsule prize on a Bulky Vendor" },
  { name: "KH2: Atlantica tutorial" },
  { name: "KH2: Use 7 different limits" },
  { name: "KH2: Use Beast's limit" },
  { name: "KH2: Use Mulan's limit" },
  { name: "KH2: Use Auron's limit" },
  { name: "KH2: Use Jack Sparrow's limit" },
  { name: "KH2: Use Aladdin's limit" },
  { name: "KH2: Use Jack Skellington's limit" },
  { name: "KH2: Use Simba's limit" },
  { name: "KH2: Use Tron's limit" },
  { name: "KH2: Use a summon limit" },
  { name: "KH2: Obtain a Struggle weapon" },
  { name: "KH2: Defeat Twilight Thorn" },
  { name: "KH2: Defeat Seifer in the back alley as Roxas" },
  { name: "KH2: Win the Struggle against Hayner" },
  { name: "KH2: Win the Struggle against Vivi" },
  { name: "KH2: Defeat Axel 1 as Roxas" },
  { name: "KH2: Win the Struggle against Setzer" },
  { name: "KH2: Go to Sunset Hill as Roxas" },
  { name: "KH2: Enter Namine's Room as Roxas" },
  { name: "KH2: Defeat Axel 2 as Roxas" },
  { name: "KH2: Destroy all tents in Shang's Camp" },
  { name: "KH2: Complete all of Shang's missions" },
  { name: "KH2: Complete the mountain climb in Land of Dragons" },
  { name: "KH2: Beat cave fight in LOD1" },
  { name: "KH2: Beat summit fight in LOD1" },
  { name: "KH2: Defeat Shan Yu" },
  { name: "KH2: Defeat Riku in LOD" },
  { name: "KH2: Go to Throne Room in LOD" },
  { name: "KH2: Defeat Storm Rider" },
  { name: "KH2: Beat Hades Escape" },
  { name: "KH2: Defeat Cerberus" },
  { name: "KH2: Complete Phil's urn training" },
  { name: "KH2: Beat Demyx in OC1" },
  { name: "KH2: Beat Pete in OC1" },
  { name: "KH2: Defeat Hydra" },
  { name: "KH2: Beat Hades Cup in OC2" },
  { name: "KH2: Auron's Statue check in OC2" },
  { name: "KH2: Defeat Hades" },
  { name: "KH2: Destroy the armor statues in the West Hall of Beast's Castle" },
  { name: "KH2: Defeat Thresholder" },
  { name: "KH2: Complete Cogsworth minigame" },
  { name: "KH2: Examine Beast's rose" },
  { name: "KH2: Defeat Dark Thorn" },
  { name: "KH2: Rumbling Rose check in BC2" },
  { name: "KH2: Defeat Xaldin in Beast's Castle" },
  { name: "KH2: Minnie Escort" },
  { name: "KH2: Defeat Old Pete" },
  { name: "KH2: Beat construction window in TR" },
  { name: "KH2: Beat Lilliput window in TR" },
  { name: "KH2: Beat fire window in TR" },
  { name: "KH2: Go to Mickey's house in TR" },
  { name: "KH2: Complete all windows in TR" },
  { name: "KH2: Defeat Boat Pete" },
  { name: "KH2: Defeat Future Pete" },
  { name: "KH2: Beat 1min timed fight in PR1" },
  { name: "KH2: Beat an ambush on the boat in Port Royal" },
  { name: "KH2: Complete boat fight in PR1" },
  { name: "KH2: Beat barrels section in PR1" },
  { name: "KH2: Defeat Barbossa" },
  { name: "KH2: Defeat Grim Reaper 1" },
  { name: "KH2: Collect all medallions from the gamblers in PR2" },
  { name: "KH2: Defeat Grim Reaper 2" },
  { name: "KH2: Destroy a stall for a puzzle piece in Agrabah" },
  { name: "KH2: Jump on top of the Tiger Head in Agrabah" },
  { name: "KH2: Enter the Cave of Wonders" },
  { name: "KH2: Beat falling segment in AG1" },
  { name: "KH2: Open both treasures in the Treasure Room in Agrabah" },
  { name: "KH2: Defeat Twin Lords" },
  { name: "KH2: Ride on the Carpet in Agrabah" },
  { name: "KH2: Grab all 3 puzzle pieces in the Sandswept Ruins" },
  { name: "KH2: Open both treasures in the ruined chamber in Agrabah" },
  { name: "KH2: Defeat Genie Jafar" },
  { name: "KH2: Spin the carousel in Xmas Town" },
  { name: "KH2: Defeat Prison Keeper" },
  { name: "KH2: Defeat Oogie Boogie" },
  { name: "KH2: Beat Lock, Shock, and Barrel in the present factory" },
  { name: "KH2: Beat the Present minigame in Xmas Town" },
  { name: "KH2: Defeat the Experiment" },
  { name: "KH2: Talk to Rafiki" },
  { name: "KH2: Beat the Hyenas in PL1" },
  { name: "KH2: Defeat Scar" },
  { name: "KH2: Beat the Hyenas in PL2" },
  { name: "KH2: Defeat Groundshaker" },
  { name: "KH2: Beat the cube minigame in SP1" },
  { name: "KH2: Complete Light Cycle minigame" },
  { name: "KH2: Complete screens in SP1" },
  { name: "KH2: Defeat Hostile Program" },
  { name: "KH2: Beat light cycle fight in SP2" },
  { name: "KH2: Beat 2nd forced fight (w/ Devastators) in SP2" },
  { name: "KH2: Defeat Solar Sailer Heartless" },
  { name: "KH2: Defeat Sark" },
  { name: "KH2: Defeat MCP" },
  { name: "KH2: Beat Bailey fight in HB" },
  { name: "KH2: Reach Ansem's study in Hollow Bastion" },
  { name: "KH2: Open Tifa's chest in Hollow Bastion" },
  { name: "KH2: Defeat Demyx in HB" },
  { name: "KH2: Fight with Yuffie in HB and win" },
  { name: "KH2: Fight with Tifa in HB and win" },
  { name: "KH2: Fight with Cloud in HB and win" },
  { name: "KH2: Beat 1k" },
  { name: "KH2: Open the Gull Wing chest in HB" },
  { name: "KH2: Enter Yen Sid's Tower" },
  { name: "KH2: Speak to the fairies at Yen Sid's Tower" },
  { name: "KH2: Beat sandlot fight in TT2" },
  { name: "KH2: Beat mansion fight in TT3" },
  { name: "KH2: Grab the puzzle piece in the pod room in TT" },
  { name: "KH2: Beat the Betwixt and Between fight" },
  { name: "KH2: Defeat Hayner as Sora" },
  { name: "KH2: Jump on top of a tram in Twilight Town" },
  { name: "KH2: Grab both puzzle pieces on Sunset Hill" },
  { name: "KH2: Examine the truck in TWTNW" },
  { name: "KH2: Proof of Existence" },
  { name: "KH2: Defeat Roxas in TWTNW" },
  { name: "KH2: Defeat Xigbar in TWTNW" },
  { name: "KH2: Defeat Luxord in TWTNW" },
  { name: "KH2: Defeat Saix in TWTNW" },
  { name: "KH2: Defeat Xemnas in TWTNW" },
  { name: "KH2: Save Piglet" },
  { name: "KH2: Reach the bottom of Honey Pot Hill" },
  { name: "KH2: Beat Balloon Bounce with Tigger and Roo" },
  { name: "KH2: Find Pooh in the Spooky Cave" },
  { name: "KH2: Yeet the Bear" },
  { name: "KH2: Take Roxas's keyblades" },
  { name: "KH2: Play a game with Luxord" },
  { name: "KH2: Witness Saix enter his berserk state" },
  { name: "KH2: Examine one of Namine's drawings" },
  { name: "KH2: Touch the beam in Twilight Town" },
  { name: "KH2: Turn one portal pink" },
  { name: "KH2: Obtain Beast as a party member" },
  { name: "KH2: Obtain Jack Skellington as a party member" },
  { name: "KH2: Obtain Simba as a party member" },
  { name: "KH2: Obtain Jack Sparrow as a party member" },
  { name: "KH2: Obtain Riku as a party member" },
  { name: "KH2: Obtain Aladdin as a party member" },
  { name: "KH2: Obtain Auron as a party member" },
  { name: "KH2: Obtain Mulan as a party member" },
  { name: "KH2: Collect 10 puzzle pieces" },
  { name: "KH2: Collect 20 puzzle pieces" },
  { name: "KH2: Collect 30 puzzle pieces" },
  { name: "KH2: Collect 40 puzzle pieces" },
  { name: "KH2: Collect 50 puzzle pieces" },
  { name: "KH2: Complete 1 Puzzle" },
  { name: "KH2: Collect 2 Puzzle Pieces in Triton's Throne" },
  { name: "KH2: Finny Fun" },
  { name: "KH2: Part of Your World" },
  { name: "KH2: Under the Sea" },
  { name: "KH2: Ursula's Revenge" },
  { name: "KH2: A New Day is Dawning" },
  { name: "KH2: Beat Pain and Panic Cup" },
  { name: "KH2: Beat Cerberus Cup" },
  { name: "KH2: Beat Titan Cup" },
  { name: "KH2: Beat Goddess of Fate Cup" },
  { name: "KH2: Beat the 1st CoR fight" },
  { name: "KH2: Turn the valves in CoR" },
  { name: "KH2: Beat the 2nd CoR fight" },
  { name: "KH2: Get to the Engine Chamber in CoR" },
  { name: "KH2: Open the last chest in CoR" },
  { name: "KH2: Beat Transport to Remembrance" },
  { name: "KH2: Defeat AS Zexion" },
  { name: "KH2: Defeat AS Larxene" },
  { name: "KH2: Defeat AS Vexen" },
  { name: "KH2: Defeat AS Lexaeus" },
  { name: "KH2: Defeat AS Marluxia" },
  { name: "KH2: Defeat Data Roxas" },
  { name: "KH2: Defeat Data Demyx" },
  { name: "KH2: Defeat Data Xigbar" },
  { name: "KH2: Defeat Data Saix" },
  { name: "KH2: Defeat Data Axel" },
  { name: "KH2: Defeat Data Xaldin" },
  { name: "KH2: Defeat Data Luxord" },
  { name: "KH2: Defeat Data Xemnas" },
  { name: "KH2: Defeat Sephiroth" },
  { name: "KH2: Defeat Terra" },
  { name: "KH2: Clash with Xemnas" },
  { name: "KH2: Enter the Laser Dome" },
  { name: "KH2: Use all of Genie's Limits" },
  { name: "KH2: Dual Wield Oathkeeper and Oblivion" },
  { name: "KH2: Obtain a -ga spell" },
  { name: "KH2: Bronze Crown" },
  { name: "KH2: Silver Crown" },
  { name: "KH2: Gold Crown" },
  { name: "KH2: Defeat Final Xemnas" },
  { name: "KH2: Firaga" },
  { name: "KH2: Blizzaga" },
  { name: "KH2: Thundaga" },
  { name: "KH2: Curaga" },
  { name: "KH2: Reflega" },
  { name: "KH2: Magnega" },
  { name: "KH2: Second Chance or Once More" },
  { name: "KH2: Chicken Little" },
  { name: "KH2: Stitch" },
  { name: "KH2: Genie" },
  { name: "KH2: Peter Pan" },
  { name: "KH1: Acquire All 5 Trinities" },
  { name: "KH1: Activate All Blue Trinities" },
  { name: "KH1: Activate All Yellow Trinities" },
  { name: "KH1: Activate All Green Trinities" },
  { name: "KH1: Activate All Red Trinities" },
  { name: "KH1: Activate All White Trinities" },
  { name: "KH1: Activate All Trinities in Traverse Town" },
  { name: "KH1: Activate All Trinities in Wonderland" },
  { name: "KH1: Activate All Trinities in Monstro" },
  { name: "KH1: Activate All Trinities in Olympus Coliseum" },
  { name: "KH1: Activate All Trinities in Deep Jungle" },
  { name: "KH1: Activate All Trinities in Agrabah" },
  { name: "KH1: Activate All Trinities in Hollow Bastion" },
  { name: "KH1: Activate All Trinities in Halloween Town" },
  { name: "KH1: Activate All Trinities in Neverland" },
  { name: "KH1: Acquire Blue Trinity" },
  { name: "KH1: Acquire Yellow Trinity" },
  { name: "KH1: Acquire White Trinity" },
  { name: "KH1: Acquire Red Trinity" },
  { name: "KH1: Acquire Green Trinity" },
  { name: "KH1: Seal 3 Keyholes" },
  { name: "KH1: Seal 5 Keyholes" },
  { name: "KH1: Defeat any 1 Super Boss" },
  { name: "KH1: Defeat Kurt Zisa" },
  { name: "KH1: Defeat Phantom" },
  { name: "KH1: Defeat Ice Titan" },
  { name: "KH1: Clear Wonderland" },
  { name: "KH1: Clear Agrabah" },
  { name: "KH1: Clear Monstro" },
  { name: "KH1: Clear Neverland" },
  { name: "KH1: Clear Deep Jungle" },
  { name: "KH1: Clear Atlantica" },
  { name: "KH1: Clear Hollow Bastion" },
  { name: "KH1: Clear Halloween Town" },
  { name: "KH1: Obtain Ultima Weapon or Wooden Sword" },
  { name: "KH1: Obtain Metal Chocobo, Lionheart, or One-Winged Angel" },
  { name: "KH1: Obtain Dream Sword, Rod or Shield (Any Party Members)" },
  { name: "KH1: Obtain Oathkeeper or Oblivion" },
  { name: "KH1: Obtain Diamond Dust or One-Winged Angel" },
  { name: "KH1: Obtain Metal Chocobo or Lionheart" },
  { name: "KH1: Obtain Divine Rose or Ladyluck" },
  { name: "KH1: Obtain Three Wishes or Wishing Star" },
  { name: "KH1: Obtain Fairy Harp or Crabclaw" },
  { name: "KH1: Obtain Jungleking or Pumpkinhead" },
  { name: "KH1: Obtain Olympia or Spellbinder" },
  { name: "KH1: Possess 7 Unique Keyblades Simultaneously" },
  { name: "KH1: Possess 13 Unique Keyblades Simultaneously" },
  { name: "KH1: Clear Phil Cup" },
  { name: "KH1: Clear Phil Cup Time-Trial" },
  { name: "KH1: Clear Pegasus Cup" },
  { name: "KH1: Clear Pegasus Cup Time-Trial" },
  { name: "KH1: Clear Herc Cup" },
  { name: "KH1: Clear Herc Cup-Time Trial" },
  { name: "KH1: Clear Phil, Pegasus, and Herc Cup" },
  { name: "KH1: Clear Hades Cup 40th Seed (Behemoth)" },
  { name: "KH1: Clear Hades Cup 30th Seed (Cerberus)" },
  { name: "KH1: Clear Hades Cup 20th Seed (Cloud & Leon)" },
  { name: "KH1: Clear Hades Cup 10th Seed (Hades)" },
  { name: "KH1: Find 33 Puppies" },
  { name: "KH1: Find 66 Puppies" },
  { name: "KH1: Find 99 Puppies" },
  { name: "KH1: Possess All 13 Ansem Reports Simultaneously" },
  { name: "KH1: Reach 11 MP With Donald" },
  { name: "KH1: Reach 50 STR With Sora" },
  { name: "KH1: Reach 7 MP With Goofy" },
  { name: "KH1: Reach 10 MP With Sora" },
  { name: "KH1: Find 3 Post Cards" },
  { name: "KH1: Find 7 Post Cards" },
  { name: "KH1: Find 10 Post Cards" },
  { name: "KH1: 15/20 Chests in Traverse Town" },
  { name: "KH1: 15/19 Chests in Wonderland" },
  { name: "KH1: 15/37 Chests in Agrabah" },
  { name: "KH1: 20/25 Chests in End of the World" },
  { name: "KH1: 15/19 Chests in Halloween Town" },
  { name: "KH1: 25/37 Chests in Hollow Bastion" },
  { name: "KH1: 5/10 Chests in World Terminus" },
  { name: "KH1: 3/5 Chests in Olympus Coliseum" },
  { name: "KH1: All 20 Chests in Traverse Town" },
  { name: "KH1: All 19 Chests in Wonderland" },
  { name: "KH1: All 19 Chests in Deep Jungle" },
  { name: "KH1: All 6 Chests in Olympus Coliseum" },
  { name: "KH1: All 21 Chests in Cave of Wonders" },
  { name: "KH1: All 19 Chests in Halloween Town" },
  { name: "KH1: All 10 Chests in Neverland" },
  { name: "KH1: All 10 Chests in Final Dimension" },
  { name: "KH1: All 5 Chests in Giant Crevasse" },
  { name: "KH1: All 6 Chests in Monstro's Mouth" },
  { name: "KH1: Open a Clam 7 Times in Atlantica" },
  { name: "KH1: Ride in Lock, Shock, and Barrel's Bathtub" },
  { name: "KH1: Clear 100 Acre Woods" },
  { name: "KH1: Give Owl 5 Rare Nuts" },
  { name: "KH1: Don't Let Tigger Stomp a Single Carrot" },
  { name: "KH1: Don't Let Bees Pop Pooh's Balloon" },
  { name: "KH1: Send Pooh At Least 30m Off the Swing" },
  { name: "KH1: Lead Pooh to 3 Jars of Honey" },
  { name: "KH1: Pull Out all of Rabbit's Crops" },
  { name: "KH1: Blow up an Urchin in Atlantica" },
  { name: "KH1: Gather 50 Fruit on Jungle Slider" },
  { name: "KH1: Sora: Ars or Strike Raid" },
  { name: "KH1: Sora: Leaf Bracer or Second Chance" },
  { name: "KH1: Sora: Sonic Blade or Ripple Drive" },
  { name: "KH1: Sora: Vortex or Hurricane Blast" },
  { name: "KH1: Sora: MP Rage or MP Haste" },
  { name: "KH1: Sora: Tech Boost or Treasure Magnet" },
  { name: "KH1: Sora: Lucky Strike or Critical Plus" },
  { name: "KH1: 2 Combo Plus" },
  { name: "KH1: Sora: Slapshot or Sliding Dash" },
  { name: "KH1: Sora: Zantetsuken or Stun Impact" },
  { name: "KH1: Sora: Gravity Break or Blitz" },
  { name: "KH1: Sora: Guard or Dodgeroll" },
  { name: "KH1: Sora: Combo-Master or Counter Attack" },
  { name: "KH1: 50 Hits on a Rare Truffle" },
  { name: "KH1: 100 Hits on a Rare Truffle" },
  { name: "KH1: Get Poisoned" },
  { name: "KH1: 3 Unique Mushroom Arts" },
  { name: "KH1: 5 Unique Mushroom Arts" },
  { name: "KH1: Learn the Spell Graviga" },
  { name: "KH1: Learn the Spell Aeroga" },
  { name: "KH1: Learn the Spell Firaga" },
  { name: "KH1: Learn the Spell Blizzaga" },
  { name: "KH1: Learn the Spell Stopga" },
  { name: "KH1: Learn the Spell Thundaga" },
  { name: "KH1: Learn the Spell Curaga" },
  { name: "KH1: 1 Ga-Spell" },
  { name: "KH1: 2 Ga-Spells" },
  { name: "KH1: 3 Ga-Spells" },
  { name: "KH1: Replace all of the Books in the Library" },
  { name: "KH1: Show Merlin 7 Unique Spells (Spellbinder Check)" },
  { name: "KH1: Watch Merlin Dance" },
  { name: "KH1: Acquire Bambi" },
  { name: "KH1: Acquire Genie" },
  { name: "KH1: Acquire Mushu" },
  { name: "KH1: Acquire Dumbo" },
  { name: "KH1: Acquire Tinker Bell" },
  { name: "KH1: Acquire Simba" },
  { name: "KH1: All 6 Summons" },
  { name: "KH1: Finish the Prelims" },
  { name: "KH1: Reach Level 20" },
  { name: "KH1: Reach Level 30" },
  { name: "KH1: Reach Level 40" },
  { name: "KH1: Reach Level 50" },
  { name: "KH1: Kill a Grand Ghost" },
  { name: "KH1: Kill a Stealth Soldier" },
  { name: "KH1: Kill a Chimera" },
  { name: "KH1: Kill a Pot Scorpion" },
  { name: "KH1: Kill a Gigas Shadow" },
  { name: "KH1: Kill a Jet Balloon" },
  { name: "KH1: Kill 3 Unique Pureblood Heartless" },
  { name: "KH1: Defeat Oogie" },
  { name: "KH1: Defeat a Boss with Their World's Keyblade" },
  { name: "KH1: Defeat Anti-Sora" },
  { name: "KH1: Obtain the check from Jack's House" },
  { name: "KH1: Defeat Maleficent" },
  { name: "KH1: Defeat Dragon Maleficent" },
  { name: "KH1: Defeat a Behemoth" },
  { name: "KH1: Defeat Ursula" },
  { name: "KH1: Defeat Cloud with the Metal Chocobo or One-Winged Angel" },
  { name: "KH1: Defeat Cloud in the Herc Cup" },
  { name: "KH1: Defeat Yuffie in the Hades Cup" },
  { name: "KH1: Defeat Riku with Wooden Sword" },
  { name: "KH1: Defeat Riku in Entrance Hall" },
  { name: "KH1: Defeat Ansem-Riku in Grand Hall" },
  { name: "KH1: Blizzaga Chest in Olympus Coliseum" },
  { name: "KH1: Blizzara Chest in Olympus Coliseum" },
  { name: "KH1: Recieve an Item from Kairi in the Secret Waterway" },
  { name: "KH1: Obtain Superglide (any 2 Glides)" },
  { name: "KH1: Obtain High Jump" },
  { name: "KH1: Obtain an EXP Item" },
  { name: "KH1: Sora: Ars Arcanum or Ragnarok" },
  { name: "KH1: Obtain Glide (any 1 Glide)" },
  { name: "KH1: Sora: Obtain Trinity Limit" },
  { name: "KH1: Sora: Obtain Cheer" },
  { name: "KH1: Sora: Obtain Trinity Limit or Cheer" },
  { name: "KH1: Any Ra-Spell" },
  { name: "KH1: 3 Ra-Spells" },
  { name: "KH1: 5 Ra-Spells" },
  { name: "KH1: All Ra-Spells" },
  { name: "KH1: Talk to Belle in the Library" },
  { name: "KH1: Brew a Potion in Camp" },
  { name: "KH1: Collect a Clock Tower Door Reward" },
  { name: "KH1: Obtain Fire Arts" },
  { name: "KH1: Obtain Blizzard Arts" },
  { name: "KH1: Obtain Thunder Arts" },
  { name: "KH1: Obtain Cure Arts" },
  { name: "KH1: Obtain Stop Arts" },
  { name: "KH1: Obtain Gravity Arts" },
  { name: "KH1: Obtain Aero Arts" },
  { name: "KH1: At Least 50 Hits on Pink Agaricus" },
  { name: "KH1: Become a Heartless" },
  { name: "KH1: Visit Geppetto's House" },
  { name: "KH1: Break all Pots without Waking Pot Scorpion" },
  { name: "KH1: Open the Emblem Door in Hollow Bastion" },
  { name: "KH1: Collect all 4 Emblem Piece Checks" },
  { name: "KH1: Sora: Obtain Air Combo Plus or Combo Plus" },
  { name: "KH1: Save Aladdin From the Sand" },
  { name: "KH1: Defeat Opposite Armor" },
  { name: "KH1: Defeat Cerberus" },
  { name: "KH1: Save Jane from the Heartless" },
  { name: "KH1: Green Trinity In Monstro" },
  { name: "KH1: All 4 Chests in the Cemetery" },
  { name: "KH1: Start A Fight in the Queens Courtyard" },
  { name: "KH1: Hitch a Ride with a Dolphin" },
  { name: "KH1: Defeat Parasite Cage for the First Time" },
  { name: "KH1: Defeat Parasite Cage for the Second Time" },
  { name: "KH1: All 4 Chests in Tea Party Garden" },
  { name: "KH1: Freeze a Bubble in Hollow Bastion" },
  { name: "KH1: Ride in 4 Different Bubbles in Hollow Bastion" },
  { name: "KH1: Have Beast Join Your Party" },
  { name: "KH1: Have Ariel Join Your Party" },
  { name: "KH1: Power the Gizmo Shop" },
  { name: "KH1: Blow out the Candles in First District" },
  { name: "KH1: Light the Fire Place in the Accessory Shop" },
  { name: "KH1: Acquire Jack-In-The-Box" },
  { name: "KH1: Acquire a Slide" },
  { name: "KH1: Acquire the Entry Pass" },
  { name: "KH1: Acquire Evidence" },
  { name: "KH1: Defeat Leon with The Lionheart" },
  { name: "KH1: Activate the White Trinity in Atlantica" },
  { name: "KH1: Defeat Trickmaster" },
  { name: "KH1: Defeat Sabor 2" },
  { name: "KH1: Defeat Clayton" },
  { name: "KH1: Defeat the Tiger Head" },
  { name: "KH1: Defeat the Pot Spider" },
  { name: "KH1: Defeat Genie Jafar" },
  { name: "KH1: Open all chests in Oogie Manor" },
  { name: "KH1: Defeat Captain Hook" },
  { name: "KH1: Activate the Yellow Trinity on Hook's Ship" },
  { name: "KH1: Open the clam at King Trident's Palace" },
  { name: "KH1: Defeat the shark in Atlantica" },
  { name: "KH1: Open the castle door in Hollow Bastion" },
];

var terra = [
  { name: "Complete Mark of Mastery (Orbs)" },
  { name: "Defeat Wheelmaster" },
  { name: "Complete Cinderella Escort" },
  { name: "Defeat Symphony Master" },
  { name: "Defeat Magic Mirror" },
  { name: "Defeat Trinity Armour" },
  { name: "Complete Story Disney Town" },
  { name: "Defeat Zack 1" },
  { name: "Defeat Zack 2" },
  { name: "Defeat Experiment 221" },
  { name: "Defeat Peter Pan" },
  { name: "Defeat Jellyshade Swarm" },
  { name: "Defeat Eraqus" },
  { name: "Defeat Vanitas and Xehanort" },
  { name: "Defeat Xehanort" },
  { name: "Defeat Terranort" },
  { name: "Complete Master It's a Small World" },
  { name: "Complete Master Blast Away" },
  { name: "Complete Master Desert Paradise" },
  { name: "Complete Master Destiny Islands" },
  { name: "Complete Master Hand in Hand" },
  { name: "Complete Beginner It's a Small World" },
  { name: "Complete Beginner Blast Away" },
  { name: "Complete Beginner Desert Paradise" },
  { name: "Complete Beginner Destiny Islands" },
  { name: "Complete Beginner Hand in Hand" },
  { name: "Beat Bruisers at Fruitball" },
  { name: "Beat Chip and Dale at Fruitball" },
  { name: "Beat Captain Justice/Captain Dark at Fruitball" },
  { name: "Complete Country Chase" },
  { name: "Complete Disney Drive" },
  { name: "Complete Grand Spree" },
  { name: "Complete Castle Circuit" },
  { name: "Obtain a Shimmering Crystal" },
  { name: "Obtain a Fleeting Crystal" },
  { name: "Obtain a Pulsing Crystal" },
  { name: "Obtain a Wellspring Crystal" },
  { name: "Obtain a Soothing Crystal" },
  { name: "Obtain a Chaos Crystal" },
  { name: "Obtain Meteor Crash" },
  { name: "Obtain Dark Haze" },
  { name: "Obtain Chaos Blade" },
  { name: "Obtain Zantetsuken" },
  { name: "Obtain Ars Solum" },
  { name: "Brutal Blast" },
  { name: "Obtain Wind Cutter" },
  { name: "Obtain Sacrifice" },
  { name: "Obtain Limit Storm" },
  { name: "Obtain Geo Impact" },
  { name: "Obtain Quake" },
  { name: "Obtain Dark Firaga" },
  { name: "Obtain Warp" },
  { name: "Obtain Meteor" },
  { name: "Obtain Time Splicer" },
  { name: "Obtain Break Time" },
  { name: "Obtain Lightning Ray" },
  { name: "Obtain Bio Barrage" },
  { name: "Obtain Mini" },
  { name: "Obtain Transcendence" },
  { name: "Obtain Magnet Spiral" },
  { name: "Obtain Mega Flare" },
  { name: "Obtain Deep Freeze" },
  { name: "Obtain Collision Magnet" },
  { name: "Obtain Slot Edge" },
  { name: "Obtain Blitz" },
  { name: "Obtain Ventus D-Link Level 2" },
  { name: "Obtain Aqua D-Link Level 2" },
  { name: "Obtain Cinderella D-Link Level 2" },
  { name: "Obtain Maleficent D-Link Level 2" },
  { name: "Obtain Zack D-Link Level 2" },
  { name: "Obtain Experiment 626/Stitch D-Link Level 2" },
  { name: "Obtain Peter Pan D-Link Level 2" },
  { name: "Obtain Pete D-Link Level 2" },
  { name: "Obtain Treasure Magnet" },
  { name: "Obtain HP Prize Plus" },
  { name: "Obtain Link Prize Plus" },
  { name: "Obtain Lucky Strike" },
  { name: "Obtain HP Boost" },
  { name: "Obtain Fire Boost" },
  { name: "Obtain Blizzard Boost" },
  { name: "Obtain Thunder Boost" },
  { name: "Obtain Cure Boost" },
  { name: "Obtain Item Boost" },
  { name: "Obtain Attack Haste" },
  { name: "Obtain Magic Haste" },
  { name: "Obtain Combo F Boost" },
  { name: "Obtain Finish Boost" },
  { name: "Obtain Fire Screen" },
  { name: "Obtain Blizzard Screen" },
  { name: "Obtain Thunder Screen" },
  { name: "Obtain Dark Screen" },
  { name: "Obtain Reload Boost" },
  { name: "Obtain Defender" },
  { name: "Obtain Combo Plus" },
  { name: "Obtain Air Combo Plus" },
  { name: "Obtain EXP Chance" },
  { name: "Obtain EXP Walker" },
  { name: "Obtain Damage Syphon" },
  { name: "Obtain Second Chance" },
  { name: "Obtain Once More" },
  { name: "Obtain Leaf Bracer" },
  { name: "Obtain Quick Blitz" },
  { name: "Obtain Sliding Dash" },
  { name: "Obtain Fire Dash" },
  { name: "Obtain Sonic Blade" },
  { name: "Obtain Strike Raid" },
  { name: "Obtain Freeze Raid" },
  { name: "Obtain Fire Surge" },
  { name: "Obtain Thunder Surge" },
  { name: "Obtain Aerial Slam" },
  { name: "Obtain Poison Edge" },
  { name: "Obtain Blizzard Edge" },
  { name: "Obtain Stun Edge" },
  { name: "Obtain Fire Strike" },
  { name: "Obtain Confusion Strike" },
  { name: "Obtain Binding Strike" },
  { name: "Obtain Fire" },
  { name: "Obtain Fira" },
  { name: "Obtain Firaga" },
  { name: "Obtain Fission Firaga" },
  { name: "Obtain Blizzard" },
  { name: "Obtain Blizzara" },
  { name: "Obtain Blizzaga" },
  { name: "Obtain Thunder" },
  { name: "Obtain Thundara" },
  { name: "Obtain Thundaga" },
  { name: "Obtain Cure" },
  { name: "Obtain Cura" },
  { name: "Obtain Curaga" },
  { name: "Obtain Esuna" },
  { name: "Obtain Mine Shield" },
  { name: "Obtain Mine Square" },
  { name: "Obtain Zero Gravity" },
  { name: "Obtain Zero Gravira" },
  { name: "Obtain Zero Graviga" },
  { name: "Obtain Magnet" },
  { name: "Obtain Magnera" },
  { name: "Obtain Magnega" },
  { name: "Obtain Aero" },
  { name: "Obtain Aerora" },
  { name: "Obtain Aeroga" },
  { name: "Obtain Blackout" },
  { name: "Obtain Ignite" },
  { name: "Obtain Confuse" },
  { name: "Obtain Bind" },
  { name: "Obtain Poison" },
  { name: "Obtain Slow" },
  { name: "Obtain Stop" },
  { name: "Obtain Stopra" },
  { name: "Obtain Stopga" },
  { name: "Obtain Sleep" },
  { name: "Obtain High Jump" },
  { name: "Obtain Air Slide" },
  { name: "Obtain Ice Slide" },
  { name: "Obtain Meteor Shower" },
  { name: "Obtain Flame Salvo" },
  { name: "Obtain Chaos Snake" },
  { name: "Obtain Ragnarok" },
  { name: "Obtain Thunderstorm" },
  { name: "Obtain Photon Charge" },
  { name: "Obtain Absolute Zero" },
  { name: "Obtain Sonic Impact" },
  { name: "Obtain Renewal Block" },
  { name: "Obtain Charge Block" },
  { name: "Obtain Stun Block" },
  { name: "Obtain Poison Block" },
  { name: "Obtain Counter Hammer" },
  { name: "Obtain Payback Fang" },
  { name: "Obtain Dark Volley" },
  { name: "Obtain Sonic Shadow" },
  { name: "Obtain Ultima Cannon" },
  { name: "Obtain Heat Slash 1" },
  { name: "Obtain Rising Rock 1" },
  { name: "Obtain Gold Rush" },
  { name: "Obtain Ramuh's Judgement" },
  { name: "Obtain Rising Rock 2" },
  { name: "Obtain Twisted Hours" },
  { name: "Obtain Surprise 1" },
  { name: "Obtain Dark Star 1" },
  { name: "Obtain Heal Strike" },
  { name: "Obtain Random End" },
  { name: "Obtain Surprise 2" },
  { name: "Obtain Dark Star 2" },
  { name: "Obtain Explosion" },
  { name: "Obtain Demolition" },
  { name: "Complete Enchanted Dominion Unversed Mission" },
  { name: "Complete Castle of Dreams Unversed Mission" },
  { name: "Complete Dwarf Woodlands Unversed Mission" },
  { name: "Complete Radiant Garden Unversed Mission" },
  { name: "Complete Disney Town Unversed Mission" },
  { name: "Complete Deep Space Unversed Mission" },
  { name: "Complete Neverland Unversed Mission" },
  { name: "Complete Olympus Coliseum Unversed Mission" },
  { name: "Complete Keyblade Graveyard Unversed Mission" },
  { name: "Complete Hunny Pot Board" },
  { name: "Complete Keyblade Board" },
  { name: "Complete Royal Board" },
  { name: "Complete Secret Board" },
  { name: "Complete Spaceship Board" },
  { name: "Complete Skull Board" },
  { name: "Complete Toon Board" },
  { name: "Complete Day of Reckoning (Mirage Arena)" },
  { name: "Complete Weaver Fever (Mirage Arena)" },
  { name: "Complete Wheels of Misfortune (Mirage Arena)" },
  { name: "Complete Sinister Sentinel (Mirage Arena)" },
  { name: "Complete Dead Ringer (Mirage Arena)" },
  { name: "Complete Combined Threat (Mirage Arena)" },
  { name: "Complete Risky Riches (Mirage Arena)" },
  { name: "Complete Harsh Punishment (Mirage Arena)" },
  { name: "Complete A Time to Chill (Mirage Arena)" },
  { name: "Complete Treasure Tussle (Mirage Arena)" },
  { name: "Complete Copycat Crisis (Mirage Arena)" },
  { name: "Complete Keepers of the Arena (Mirage Arena)" },
  { name: "Complete Villains Vendetta (Mirage Arena)" },
  { name: "Complete Monster of the Sea (Mirage Arena)" },
  { name: "Complete Light's Lessons (Mirage Arena)" },
  { name: "Complete Peering into Darkness (Mirage Arena)" },
  { name: "Complete Defeat Vanitas Remnant" },
  { name: "Complete Defeat Mysterious Figure" },
];

var ventus = [
  { name: "Complete Mark of Master (Orbs)" },
  { name: "Complete Dwarfs" },
  { name: "Complete Snow White Escort" },
  { name: "Defeat Mad Treant" },
  { name: "Defeat Lucifer" },
  { name: "Defeat Maleficent" },
  { name: "Defeat Vanitas 1" },
  { name: "Defeat Trinity Armour" },
  { name: "Complete Story Disney Town" },
  { name: "Defeat Jellyshade Swarm" },
  { name: "Defeat Metamorphosis 1" },
  { name: "Defeat Metamorphosis 2" },
  { name: "Defeat Hook" },
  { name: "Defeat Vanitas 2" },
  { name: "Defeat Final Vanitas" },
  { name: "Complete Master It's a Small World" },
  { name: "Complete Master Blast Away" },
  { name: "Complete Master Desert Paradise" },
  { name: "Complete Master Destiny Islands" },
  { name: "Complete Master Hand in Hand" },
  { name: "Complete Beginner It's a Small World" },
  { name: "Complete Beginner Blast Away" },
  { name: "Complete Beginner Desert Paradise" },
  { name: "Complete Beginner Destiny Islands" },
  { name: "Complete Beginner Hand in Hand" },
  { name: "Beat Bruisers at Fruitball" },
  { name: "Beat Chip and Dale at Fruitball" },
  { name: "Beat Captain Justice/Captain Dark at Fruitball" },
  { name: "Complete Country Chase" },
  { name: "Complete Disney Drive" },
  { name: "Complete Grand Spree" },
  { name: "Complete Castle Circuit" },
  { name: "Obtain a Shimmering Crystal" },
  { name: "Obtain a Fleeting Crystal" },
  { name: "Obtain a Pulsing Crystal" },
  { name: "Obtain a Wellspring Crystal" },
  { name: "Obtain a Soothing Crystal" },
  { name: "Obtain a Chaos Crystal" },
  { name: "Obtain Spark Raid" },
  { name: "Obtain Wind Raid" },
  { name: "Obtain Ars Arcanum" },
  { name: "Obtain Tornado Strike" },
  { name: "Obtain Salvation" },
  { name: "Obtain Faith" },
  { name: "Obtain Tornado" },
  { name: "Obtain Time Splicer" },
  { name: "Obtain Break Time" },
  { name: "Obtain Lightning Ray" },
  { name: "Obtain Bio Barrage" },
  { name: "Obtain Mini" },
  { name: "Obtain Transcendence" },
  { name: "Obtain Magnet Spiral" },
  { name: "Obtain Mega Flare" },
  { name: "Obtain Deep Freeze" },
  { name: "Obtain Collision Magnet" },
  { name: "Obtain Slot Edge" },
  { name: "Obtain Blitz" },
  { name: "Obtain Terra D-Link Level 2" },
  { name: "Obtain Aqua D-Link Level 2" },
  { name: "Obtain Mickey D-Link Level 2" },
  { name: "Obtain Goofy D-Link Level 2" },
  { name: "Obtain Donald D-Link Level 2" },
  { name: "Obtain Snow White D-Link Level 2" },
  { name: "Obtain Cinderella D-Link Level 2" },
  { name: "Obtain Zack D-Link Level 2" },
  { name: "Obtain Experiment 626/Stitch D-Link Level 2" },
  { name: "Obtain Peter Pan D-Link Level 2" },
  { name: "Obtain Pete D-Link Level 2" },
  { name: "Obtain Treasure Magnet" },
  { name: "Obtain HP Prize Plus" },
  { name: "Obtain Link Prize Plus" },
  { name: "Obtain Lucky Strike" },
  { name: "Obtain HP Boost" },
  { name: "Obtain Fire Boost" },
  { name: "Obtain Blizzard Boost" },
  { name: "Obtain Thunder Boost" },
  { name: "Obtain Cure Boost" },
  { name: "Obtain Item Boost" },
  { name: "Obtain Attack Haste" },
  { name: "Obtain Magic Haste" },
  { name: "Obtain Combo F Boost" },
  { name: "Obtain Finish Boost" },
  { name: "Obtain Fire Screen" },
  { name: "Obtain Blizzard Screen" },
  { name: "Obtain Thunder Screen" },
  { name: "Obtain Dark Screen" },
  { name: "Obtain Reload Boost" },
  { name: "Obtain Defender" },
  { name: "Obtain Combo Plus" },
  { name: "Obtain Air Combo Plus" },
  { name: "Obtain EXP Chance" },
  { name: "Obtain EXP Walker" },
  { name: "Obtain Damage Syphon" },
  { name: "Obtain Second Chance" },
  { name: "Obtain Once More" },
  { name: "Obtain Leaf Bracer" },
  { name: "Obtain Quick Blitz" },
  { name: "Obtain Sliding Dash" },
  { name: "Obtain Fire Dash" },
  { name: "Obtain Sonic Blade" },
  { name: "Obtain Strike Raid" },
  { name: "Obtain Freeze Raid" },
  { name: "Obtain Fire Surge" },
  { name: "Obtain Thunder Surge" },
  { name: "Obtain Aerial Slam" },
  { name: "Obtain Poison Edge" },
  { name: "Obtain Blizzard Edge" },
  { name: "Obtain Stun Edge" },
  { name: "Obtain Fire Strike" },
  { name: "Obtain Confusion Strike" },
  { name: "Obtain Binding Strike" },
  { name: "Obtain Fire" },
  { name: "Obtain Fira" },
  { name: "Obtain Firaga" },
  { name: "Obtain Fission Firaga" },
  { name: "Obtain Blizzard" },
  { name: "Obtain Blizzara" },
  { name: "Obtain Blizzaga" },
  { name: "Obtain Thunder" },
  { name: "Obtain Thundara" },
  { name: "Obtain Thundaga" },
  { name: "Obtain Cure" },
  { name: "Obtain Cura" },
  { name: "Obtain Curaga" },
  { name: "Obtain Esuna" },
  { name: "Obtain Mine Shield" },
  { name: "Obtain Mine Square" },
  { name: "Obtain Zero Gravity" },
  { name: "Obtain Zero Gravira" },
  { name: "Obtain Zero Graviga" },
  { name: "Obtain Magnet" },
  { name: "Obtain Magnera" },
  { name: "Obtain Magnega" },
  { name: "Obtain Aero" },
  { name: "Obtain Aerora" },
  { name: "Obtain Aeroga" },
  { name: "Obtain Blackout" },
  { name: "Obtain Ignite" },
  { name: "Obtain Confuse" },
  { name: "Obtain Bind" },
  { name: "Obtain Poison" },
  { name: "Obtain Slow" },
  { name: "Obtain Stop" },
  { name: "Obtain Stopra" },
  { name: "Obtain Stopga" },
  { name: "Obtain Sleep" },
  { name: "Obtain High Jump" },
  { name: "Obtain Air Slide" },
  { name: "Obtain Ice Slide" },
  { name: "Obtain Meteor Shower" },
  { name: "Obtain Flame Salvo" },
  { name: "Obtain Chaos Snake" },
  { name: "Obtain Ragnarok" },
  { name: "Obtain Thunderstorm" },
  { name: "Obtain Photon Charge" },
  { name: "Obtain Absolute Zero" },
  { name: "Obtain Thunderroll" },
  { name: "Obtain Reversal" },
  { name: "Obtain Glide" },
  { name: "Obtain Super Glide" },
  { name: "Obtain Fire Glide" },
  { name: "Obtain Homing Slide" },
  { name: "Obtain Renewal Block" },
  { name: "Obtain Charge Block" },
  { name: "Obtain Stun Block" },
  { name: "Obtain Poison Block" },
  { name: "Obtain Counter Rush" },
  { name: "Obtain Reversal Slash" },
  { name: "Obtain Payback Raid" },
  { name: "Obtain Pulse Bomb" },
  { name: "Obtain Multivortex" },
  { name: "Obtain Heat Slash 1" },
  { name: "Obtain Air Flair 1" },
  { name: "Obtain Gold Rush" },
  { name: "Obtain Ramuh's Judgement" },
  { name: "Obtain Air Flair 2" },
  { name: "Obtain Twisted Hours" },
  { name: "Obtain Surprise 1" },
  { name: "Obtain Air Flair 3" },
  { name: "Obtain Heal Strike" },
  { name: "Obtain Surprise 2" },
  { name: "Obtain Air Flair 4" },
  { name: "Obtain Explosion" },
  { name: "Obtain Celebration" },
  { name: "Obtain Stratosphere" },
  { name: "Complete Enchanted Dominion Unversed Mission" },
  { name: "Complete Castle of Dreams Unversed Mission" },
  { name: "Complete Dwarf Woodlands Unversed Mission" },
  { name: "Complete Radiant Garden Unversed Mission" },
  { name: "Complete Disney Town Unversed Mission" },
  { name: "Complete Deep Space Unversed Mission" },
  { name: "Complete Neverland Unversed Mission" },
  { name: "Complete Olympus Coliseum Unversed Mission" },
  { name: "Complete Keyblade Graveyard Unversed Mission" },
  { name: "Complete Hunny Pot Board" },
  { name: "Complete Keyblade Board" },
  { name: "Complete Royal Board" },
  { name: "Complete Secret Board" },
  { name: "Complete Spaceship Board" },
  { name: "Complete Skull Board" },
  { name: "Complete Toon Board" },
  { name: "Complete Day of Reckoning (Mirage Arena)" },
  { name: "Complete Weaver Fever (Mirage Arena)" },
  { name: "Complete Wheels of Misfortune (Mirage Arena)" },
  { name: "Complete Sinister Sentinel (Mirage Arena)" },
  { name: "Complete Dead Ringer (Mirage Arena)" },
  { name: "Complete Combined Threat (Mirage Arena)" },
  { name: "Complete Risky Riches (Mirage Arena)" },
  { name: "Complete Harsh Punishment (Mirage Arena)" },
  { name: "Complete A Time to Chill (Mirage Arena)" },
  { name: "Complete Treasure Tussle (Mirage Arena)" },
  { name: "Complete Copycat Crisis (Mirage Arena)" },
  { name: "Complete Keepers of the Arena (Mirage Arena)" },
  { name: "Complete Villains Vendetta (Mirage Arena)" },
  { name: "Complete Monster of the Sea (Mirage Arena)" },
  { name: "Complete Light's Lessons (Mirage Arena)" },
  { name: "Complete Peering into Darkness (Mirage Arena)" },
  { name: "Complete Defeat Vanitas Remnant" },
  { name: "Complete Defeat Mysterious Figure" },
];

var aqua = [
  { name: "Complete Mark of Mastery (Orbs)" },
  { name: "Complete Jaq Escort" },
  { name: "Defeat Cursed Coach" },
  { name: "Defeat Magic Mirror" },
  { name: "Defeat Dragon Maleficent" },
  { name: "Defeat Trinity Armour" },
  { name: "Defeat Vanitas 1" },
  { name: "Complete Story Disney Town" },
  { name: "Defeat Zack" },
  { name: "Defeat Hades and Ice Colossus" },
  { name: "Brave Gotcha, Take that" },
  { name: "Defeat Gantu" },
  { name: "Defeat Vanitas 2" },
  { name: "Defeat Venitas" },
  { name: "Complete Master It's a Small World" },
  { name: "Complete Master Blast Away" },
  { name: "Complete Master Desert Paradise" },
  { name: "Complete Master Destiny Islands" },
  { name: "Complete Master Hand in Hand" },
  { name: "Complete Beginner It's a Small World" },
  { name: "Complete Beginner Blast Away" },
  { name: "Complete Beginner Desert Paradise" },
  { name: "Complete Beginner Destiny Islands" },
  { name: "Complete Beginner Hand in Hand" },
  { name: "Beat Bruisers at Fruitball" },
  { name: "Beat Chip and Dale at Fruitball" },
  { name: "Beat Captain Justice/Captain Dark at Fruitball" },
  { name: "Complete Country Chase" },
  { name: "Complete Disney Drive" },
  { name: "Complete Grand Spree" },
  { name: "Complete Castle Circuit" },
  { name: "Obtain a Shimmering Crystal" },
  { name: "Obtain a Fleeting Crystal" },
  { name: "Obtain a Pulsing Crystal" },
  { name: "Obtain a Wellspring Crystal" },
  { name: "Obtain a Soothing Crystal" },
  { name: "Obtain a Chaos Crystal" },
  { name: "Obtain Triple Firaga" },
  { name: "Obtain Triple Blizzaga" },
  { name: "Obtain Thundaga Shot" },
  { name: "Obtain Munny Magnet" },
  { name: "Obtain Energy Magnet" },
  { name: "Obtain D-Link Magnet" },
  { name: "Obtain Glacier" },
  { name: "Obtain Ice Barrage" },
  { name: "Obtain Friaga Burst" },
  { name: "Obtain Raging Storm" },
  { name: "Obtain Magic Hour" },
  { name: "Obtain Time Splicer" },
  { name: "Obtain Break Time" },
  { name: "Obtain Lightning Ray" },
  { name: "Obtain Bio Barrage" },
  { name: "Obtain Mini" },
  { name: "Obtain Transcendence" },
  { name: "Obtain Magnet Spiral" },
  { name: "Obtain Mega Flare" },
  { name: "Obtain Deep Freeze" },
  { name: "Obtain Collision Magnet" },
  { name: "Obtain Slot Edge" },
  { name: "Obtain Blitz" },
  { name: "Obtain Terra D-Link Level 2" },
  { name: "Obtain Ventus D-Link Level 2" },
  { name: "Obtain Mickey D-Link Level 2" },
  { name: "Obtain Goofy D-Link Level 2" },
  { name: "Obtain Donald D-Link Level 2" },
  { name: "Obtain Snow White D-Link Level 2" },
  { name: "Obtain Cinderella D-Link Level 2" },
  { name: "Obtain Zack D-Link Level 2" },
  { name: "Obtain Experiment 626/Stitch D-Link Level 2" },
  { name: "Obtain Peter Pan D-Link Level 2" },
  { name: "Obtain Pete D-Link Level 2" },
  { name: "Obtain Treasure Magnet" },
  { name: "Obtain HP Prize Plus" },
  { name: "Obtain Link Prize Plus" },
  { name: "Obtain Lucky Strike" },
  { name: "Obtain HP Boost" },
  { name: "Obtain Fire Boost" },
  { name: "Obtain Blizzard Boost" },
  { name: "Obtain Thunder Boost" },
  { name: "Obtain Cure Boost" },
  { name: "Obtain Item Boost" },
  { name: "Obtain Attack Haste" },
  { name: "Obtain Magic Haste" },
  { name: "Obtain Combo F Boost" },
  { name: "Obtain Finish Boost" },
  { name: "Obtain Fire Screen" },
  { name: "Obtain Blizzard Screen" },
  { name: "Obtain Thunder Screen" },
  { name: "Obtain Dark Screen" },
  { name: "Obtain Reload Boost" },
  { name: "Obtain Defender" },
  { name: "Obtain Combo Plus" },
  { name: "Obtain Air Combo Plus" },
  { name: "Obtain EXP Chance" },
  { name: "Obtain EXP Walker" },
  { name: "Obtain Damage Syphon" },
  { name: "Obtain Second Chance" },
  { name: "Obtain Once More" },
  { name: "Obtain Leaf Bracer" },
  { name: "Obtain Barrier Surge" },
  { name: "Obtain Quick Blitz" },
  { name: "Obtain Sliding Dash" },
  { name: "Obtain Fire Dash" },
  { name: "Obtain Sonic Blade" },
  { name: "Obtain Strike Raid" },
  { name: "Obtain Freeze Raid" },
  { name: "Obtain Fire Surge" },
  { name: "Obtain Thunder Surge" },
  { name: "Obtain Aerial Slam" },
  { name: "Obtain Poison Edge" },
  { name: "Obtain Blizzard Edge" },
  { name: "Obtain Stun Edge" },
  { name: "Obtain Fire Strike" },
  { name: "Obtain Confusion Strike" },
  { name: "Obtain Binding Strike" },
  { name: "Obtain Fire" },
  { name: "Obtain Fira" },
  { name: "Obtain Firaga" },
  { name: "Obtain Fission Firaga" },
  { name: "Obtain Blizzard" },
  { name: "Obtain Blizzara" },
  { name: "Obtain Blizzaga" },
  { name: "Obtain Thunder" },
  { name: "Obtain Thundara" },
  { name: "Obtain Thundaga" },
  { name: "Obtain Cure" },
  { name: "Obtain Cura" },
  { name: "Obtain Curaga" },
  { name: "Obtain Esuna" },
  { name: "Obtain Mine Shield" },
  { name: "Obtain Mine Square" },
  { name: "Obtain Zero Gravity" },
  { name: "Obtain Zero Gravira" },
  { name: "Obtain Zero Graviga" },
  { name: "Obtain Magnet" },
  { name: "Obtain Magnera" },
  { name: "Obtain Magnega" },
  { name: "Obtain Aero" },
  { name: "Obtain Aerora" },
  { name: "Obtain Aeroga" },
  { name: "Obtain Blackout" },
  { name: "Obtain Ignite" },
  { name: "Obtain Confuse" },
  { name: "Obtain Bind" },
  { name: "Obtain Poison" },
  { name: "Obtain Slow" },
  { name: "Obtain Stop" },
  { name: "Obtain Stopra" },
  { name: "Obtain Stopga" },
  { name: "Obtain Sleep" },
  { name: "Obtain High Jump" },
  { name: "Obtain Air Slide" },
  { name: "Obtain Ice Slide" },
  { name: "Obtain Meteor Shower" },
  { name: "Obtain Flame Salvo" },
  { name: "Obtain Chaos Snake" },
  { name: "Obtain Ragnarok" },
  { name: "Obtain Thunderstorm" },
  { name: "Obtain Photon Charge" },
  { name: "Obtain Absolute Zero" },
  { name: "Obtain Wishing Edge" },
  { name: "Obtain Seeker Mine" },
  { name: "Obtain Firewheel" },
  { name: "Obtain Homing Slide" },
  { name: "Obtain Teleport" },
  { name: "Obtain Doubleflight" },
  { name: "Obtain Renewal Barrier" },
  { name: "Obtain Charge Barrier" },
  { name: "Obtain Confuse Barrier" },
  { name: "Obtain Stop Barrier" },
  { name: "Obtain Counter Blast" },
  { name: "Obtain Payback Surge" },
  { name: "Obtain Bubble Blaster" },
  { name: "Obtain Prism Rain" },
  { name: "Obtain Lightbloom" },
  { name: "Obtain Heat Slash 1" },
  { name: "Obtain Magic Pulse 1" },
  { name: "Obtain Gold Rush" },
  { name: "Obtain Heat Slash 2" },
  { name: "Obtain Ramuh's Judgement" },
  { name: "Obtain Magic Pulse 2" },
  { name: "Obtain Twisted Hours" },
  { name: "Obtain Surprise 1" },
  { name: "Obtain Magic Pulse 3" },
  { name: "Obtain Heal Strike" },
  { name: "Obtain Surprise 2" },
  { name: "Obtain Magic Pulse 4" },
  { name: "Obtain Explosion" },
  { name: "Obtain Ice Burst" },
  { name: "Obtain Teleport Strike" },
  { name: "Complete Enchanted Dominion Unversed Mission" },
  { name: "Complete Castle of Dreams Unversed Mission" },
  { name: "Complete Dwarf Woodlands Unversed Mission" },
  { name: "Complete Radiant Garden Unversed Mission" },
  { name: "Complete Disney Town Unversed Mission" },
  { name: "Complete Deep Space Unversed Mission" },
  { name: "Complete Neverland Unversed Mission" },
  { name: "Complete Olympus Coliseum Unversed Mission" },
  { name: "Complete Keyblade Graveyard Unversed Mission" },
  { name: "Complete Hunny Pot Board" },
  { name: "Complete Keyblade Board" },
  { name: "Complete Royal Board" },
  { name: "Complete Secret Board" },
  { name: "Complete Spaceship Board" },
  { name: "Complete Skull Board" },
  { name: "Complete Toon Board" },
  { name: "Complete Day of Reckoning (Mirage Arena)" },
  { name: "Complete Weaver Fever (Mirage Arena)" },
  { name: "Complete Wheels of Misfortune (Mirage Arena)" },
  { name: "Complete Sinister Sentinel (Mirage Arena)" },
  { name: "Complete Dead Ringer (Mirage Arena)" },
  { name: "Complete Combined Threat (Mirage Arena)" },
  { name: "Complete Risky Riches (Mirage Arena)" },
  { name: "Complete Harsh Punishment (Mirage Arena)" },
  { name: "Complete A Time to Chill (Mirage Arena)" },
  { name: "Complete Treasure Tussle (Mirage Arena)" },
  { name: "Complete Copycat Crisis (Mirage Arena)" },
  { name: "Complete Keepers of the Arena (Mirage Arena)" },
  { name: "Complete Villains Vendetta (Mirage Arena)" },
  { name: "Complete Monster of the Sea (Mirage Arena)" },
  { name: "Complete Light's Lessons (Mirage Arena)" },
  { name: "Complete Peering into Darkness (Mirage Arena)" },
  { name: "Complete Defeat Vanitas Remnant" },
  { name: "Complete Defeat Mysterious Figure" },
];

var kh3goals = [
  { name: "Defeat the Rock Troll in Olympus" },
  { name: "Defeat Rock Titan" },
  { name: "Defeat Ice and Lava Titans" },
  { name: "Defeat Torando Titan" },
  { name: "Defeat Demon Tide in Twilight Town" },
  { name: "Defeat Angelic Amber" },
  { name: "Defeat the UFO in Toy Box" },
  { name: "Defeat the King of Toys" },
  { name: "Defeat Chaos Carriage" },
  { name: "Defeat Grim Guardianess" },
  { name: "Defeat Lump of Horror" },
  { name: "Defeat the Rock Troll in Arendelle" },
  { name: "Escape the Labyrinth of Ice" },
  { name: "Defeat Marshamllow" },
  { name: "Defeat Skoll" },
  { name: "Defeat the Raging Vulture" },
  { name: "Defeat the Lightning Angler" },
  { name: "Defeat the Kraken" },
  { name: "Defeat Davy Jones" },
  { name: "Defeat the Metal Troll" },
  { name: "Defeat the Catastrochorus" },
  { name: "Defeat the Darkubes" },
  { name: "Defeat Dark Baymax" },
  { name: "Defeat Dark Riku and Xigbar" },
  { name: "Defeat Luxord, Marluxia, and Larxene" },
  { name: "Defeat Vanitas and Terra-Xehanort" },
  { name: "Defeat Saix" },
  { name: "Defeat Ansem, Xemnas, and Young Xehanort" },
  { name: "Obtain Hercules as a party member" },
  { name: "Obtain Woody and Buzz as party members" },
  { name: "Obtain Rapunzel and Flynn as party members" },
  { name: "Obtain Mike and Sulley as party members" },
  { name: "Obtain Marshmallow as a party member" },
  { name: "Obtain Jack Sparrow as a party member" },
  { name: "Obtain Baymax as a party member" },
  { name: "Collect 10 emblems" },
  { name: "Collect 20 emblems" },
  { name: "Collect 30 emblems" },
  { name: "Collect 40 emblems" },
  { name: "Collect 50 emblems" },
  { name: "Collect 60 emblems" },
  { name: "Collect 70 emblems" },
  { name: "Collect 80 emblems" },
  { name: "Collect 90 emblems" },
  { name: "All Olympus emblems" },
  { name: "All Twilight Town emblems" },
  { name: "All Toy Box emblems" },
  { name: "All Corona emblems" },
  { name: "All Monstropolis emblems" },
  { name: "All Arendelle emblems" },
  { name: "All Carribean emblems" },
  { name: "All San Fran emblems" },
  { name: "5 Olympus emblems" },
  { name: "5 Twilight Town emblems" },
  { name: "5 Toy Box emblems" },
  { name: "5 Corona emblems" },
  { name: "5 Monstropolis emblems" },
  { name: "5 Arendelle emblems" },
  { name: "5 Carribean emblems" },
  { name: "5 San Fran emblems" },
  { name: "All Olympus chests" },
  { name: "All Twilight Town chests" },
  { name: "All Toy Box chests" },
  { name: "All Corona chests" },
  { name: "All Monstropolis chests" },
  { name: "All Arendelle chests" },
  { name: "All Carribean chests" },
  { name: "All San Fran chests" },
  { name: "10 Olympus chests" },
  { name: "20 Olympus chests" },
  { name: "30 Olympus chests" },
  { name: "5 Twilight Town chests" },
  { name: "10 Toy Box chests" },
  { name: "20 Toy Box chests" },
  { name: "10 Corona chests" },
  { name: "20 Corona chests" },
  { name: "10 Monstropolis chests" },
  { name: "20 Monstropolis chests" },
  { name: "10 Arendelle chests" },
  { name: "20 Arendelle chests" },
  { name: "10 Carribean chests" },
  { name: "20 Carribean chests" },
  { name: "30 Carribean chests" },
  { name: "40 Carribean chests" },
  { name: "50 Carribean chests" },
  { name: "10 San Fran chests" },
  { name: "20 San Fran chests" },
  { name: "30 San Fran chests" },
  { name: "Collect 25 chests" },
  { name: "Collect 50 chests" },
  { name: "Collect 75 chests" },
  { name: "Collect 100 chests" },
  { name: "Collect 125 chests" },
  { name: "Collect 150 chests" },
  { name: "3 photo missions" },
  { name: "5 photo missions" },
  { name: "7 photo missions" },
  { name: "10 photo missions" },
  { name: "Cherry Flan" },
  { name: "Strawberry Flan" },
  { name: "Orange Flan" },
  { name: "Banana Flan" },
  { name: "Grape Flan" },
  { name: "Watermelon Flan" },
  { name: "Honeydew Flan" },
  { name: "3 Flans" },
  { name: "Flantastic Seven" },
  { name: "2 Frozen Slider Treasures" },
  { name: "5 Frozen Slider Treasures" },
  { name: "7 Frozen Slider Treasures" },
  { name: "10 Frozen Slider Treasures" },
  { name: "Frozen Slider A Rank" },
  { name: "Flash Tracer Fred A Rank" },
  { name: "Flash Tracer Gogo A Rank" },
  { name: "Tigger’s Vegetables excellent" },
  { name: "Lumpy’s Fruit excellent" },
  { name: "Pooh’s Hunny excellent" },
  { name: "Festival Dance A Rank" },
  { name: "5 Classic Kingdom" },
  { name: "10 Classic Kingdom" },
  { name: "Synth 5 unique items" },
  { name: "Synth a weapon" },
  { name: "Synth an armor" },
  { name: "Synth an accessory" },
  { name: "Fully upgrade 1 keyblade" },
  { name: "Level 3 Keyblade" },
  { name: "Level 4 Keyblade" },
  { name: "Level 5 Keyblade" },
  { name: "Level 7 Keyblade" },
  { name: "Level 8 Keyblade" },
  { name: "Level 9 Keyblade" },
  { name: "Cook 2 starters" },
  { name: "Cook 2 soups" },
  { name: "Cook 2 fish" },
  { name: "Cook 2 meat" },
  { name: "Cook 2 desserts" },
  { name: "Cook 2 secret menu items" },
  { name: "Cook 2 chopping foods" },
  { name: "Cook 2 flambe foods" },
  { name: "Cook 2 egg cracking foods" },
  { name: "Cook 2 seasoning foods" },
  { name: "1 Star Bistro" },
  { name: "2 Stars Bistro" },
  { name: "3 Stars Bistro" },
  { name: "4 Stars Bistro" },
  { name: "5 Stars Bistro" },
  { name: "1 boss selfie" },
  { name: "2 boss selfies" },
  { name: "3 boss selfies" },
  { name: "Donald selfie" },
  { name: "Goofy selfie" },
  { name: "Herc selfie" },
  { name: "Woody selfie" },
  { name: "Buzz selfie" },
  { name: "Flynn selfie" },
  { name: "Rapunzel selfie" },
  { name: "Mike selfie" },
  { name: "Sully selfie" },
  { name: "Marshmallow selfie" },
  { name: "Jack Sparrow selfie" },
  { name: "Baymax selfie" },
  { name: "Defeat 100 shadows" },
  { name: "Defeat 100 toy troopers" },
  { name: "Defeat 50 powerwilds" },
  { name: "Defeat 100 puffballs" },
  { name: "Defeat 50 mary poppins" },
  { name: "Defeat 50 winterhorns" },
  { name: "Defeat 10 frost serpants" },
  { name: "Defeat 10 spiked turtletoads" },
  { name: "Defeat 10 turtletoads" },
  { name: "Obtain all rosette armor" },
  { name: "Obtain 3 rosette armor" },
  { name: "Obtain every element cufflink" },
  { name: "Obtain 3 element cufflinks" },
  { name: "Obtain 1 + accessory" },
  { name: "Obtain 3 staves" },
  { name: "Obtain 3 shields" },
  { name: "Obtain Hero’s Belt" },
  { name: "Obtain 2 earrings" },
  { name: "50 ethers" },
  { name: "20 unique ingredients" },
  { name: "20k munny" },
  { name: "Save 1 person in Olympus" },
  { name: "Save 2 people in Olympus" },
  { name: "Save 3 people in Olympus" },
  { name: "Save 4 people in Olympus" },
  { name: "River fight in Olympus" },
  { name: "Waterfall fight in Olympus" },
  { name: "Sand storm fight in Olympus" },
  { name: "Use forge in Olympus" },
  { name: "Ride rail to Cloud Ridge" },
  { name: "3 barrels in Olympus" },
  { name: "3 barrels in Twilight Town" },
  { name: "Jump on 6 TT mansion columns" },
  { name: "Use ball in Andy’s room" },
  { name: "Inhale helium three times" },
  { name: "Toy Box toy fighting game chest" },
  { name: "Toy Box ball pit swing" },
  { name: "Use aero on dandelions" },
  { name: "Save bunnies in Corona" },
  { name: "Splash Rapunzel" },
  { name: "Lead birds to Rapunzel" },
  { name: "All enemies and chest in Corona cave" },
  { name: "Swing with Rapunzel 3 times" },
  { name: "Emblem and chest in Corona mine" },
  { name: "Catch 4 fish in Corona" },
  { name: "3 barrels in Corona" },
  { name: "Hit three snack machines in Monstropolis" },
  { name: "Deer fight in Arendelle" },
  { name: "Ride 5 snowballs" },
  { name: "Find Olaf again" },
  { name: "Sail to Ship’s End" },
  { name: "Sail to Sandbar Isle" },
  { name: "Sail to Exile Island" },
  { name: "Sail to Gateway of Regret" },
  { name: "Sail to Isla de los Mastiles" },
  { name: "Sail to Confinement Isle" },
  { name: "Sail to Horseshoe Island" },
  { name: "Sail to Isle of Luck" },
  { name: "Sail to Isla Verdemontana" },
  { name: "Crystal Snow" },
  { name: "Ever After" },
  { name: "Favorite Deputy" },
  { name: "Happy Gear" },
  { name: "Hero's Origin" },
  { name: "Nano Gear" },
  { name: "Oathkeeper" },
  { name: "Oblivion" },
  { name: "Shooting Star" },
  { name: "Starlight" },
  { name: "Ultima Weapon" },
  { name: "Wheel of Fate" },
  { name: "Hunny Spout" },
  { name: "Grand Chef" },
  { name: "Classic Tone" },
  { name: "Fire" },
  { name: "Fira" },
  { name: "Firaga" },
  { name: "Blizzard" },
  { name: "Blizzara" },
  { name: "Blizzaga" },
  { name: "Thunder" },
  { name: "Thundara" },
  { name: "Thundaga" },
  { name: "Cure" },
  { name: "Cura" },
  { name: "Curaga" },
  { name: "Aero" },
  { name: "Aerora" },
  { name: "Aeroga" },
  { name: "Water" },
  { name: "Watera" },
  { name: "Waterga" },
  { name: "Ralph" },
  { name: "Simba" },
  { name: "Ariel" },
  { name: "Meow Wow" },
  { name: "Stitch" },
];
